CAM-13835: doc(quarkus): add quarkus extension config docs
camunda/camunda-docs-manual pull request #1046
Opened 2021-08-23 12:34 UTC by koevskinikola

* This page documents the configuration options for an embedded process engine in a Quarkus application. It covers configuration methods for a process engine, job executor, and data source.

Related to CAM-13835

:information_source: This PR is based on the CAM-13638 branch.

2021-08-23 12:36 UTC, koevskinikola commented on content/user-guide/quarkus-integration/configuration.md
> +* No JDBC configuration is present. A Quarkus datasource should be configured and used.
@tasso94 I documented the defaults that we have in the `QuarkusProcessEngineConfiguration` class, however, I'm worried that this would require additional maintenance whenever we change something there. What do you think?

2021-08-24 09:14 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +* No JDBC configuration is present. A Quarkus datasource should be configured and used.
As discussed f2f: I think a developer is aware when changing a default value in a configuration class that this must be documented and will probably find the right place.

2021-08-24 09:48 UTC, tasso94 requested changes
LGTM in general. I added some review hints below:

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +  }
```suggestion
@ApplicationScoped
public class MyCustomEngineConfig extends QuarkusProcessEngineConfiguration {

  public MyCustomEngineConfig() {
    // your custom configuration is done here
    setProcessEngineName("customEngine");
  }
  
}
```

Just a wee idea. Do you consider this configuration example simpler?

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +In addition to the general process engine, and job executor, configuration properties mentioned in the previous
```suggestion
In addition to the general process engine and job executor configuration properties mentioned in the previous 
```

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +      For configuring a Quarkus Datasource, have a look on the [Quarkus Datasource][quarkus-datasource] page.
```suggestion
      For configuring a Quarkus Datasource, have a look on the <a href="https://quarkus.io/guides/datasource">Quarkus Datasource</a> page.
```

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +If not default Quarkus datasource is configured, the Camunda Quarkus extension sets an embedded (local) H2 database as
```suggestion
If no default Quarkus datasource is configured, the Camunda Quarkus extension sets an embedded (local) on-disk H2 database as 
```

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +quarkus.datasource.camunda.db-kind=h2
```suggestion
quarkus.datasource.my-datasource.db-kind=h2
```
As a user, I don't understand at first glance that `camunda` is a custom value. Let's change it to something more self-explanatory.

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +### Programmatic Process Engine Configuration
```suggestion
### Programmatic Configuration
```
This is a sub-headline of `Process Engine Configuration`. Should we remove the "Process Engine" part since the relation becomes clear due to the parent headline?
![image](https://user-images.githubusercontent.com/3015690/130595096-d94e6146-89b5-4698-992e-9d615179a587.png)

2021-08-24 09:48 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +* The `idGenerator` is set to an instance of {{< javadocref page="?org/camunda/bpm/engine/impl/persistence/StrongUuidGenerator.html" text="StrongUuidGenerator" >}}.
Reading through this now feels a bit bloated/text-heavy. Maybe we could convert it into a table and avoid the extra explanations? Like this, a user could skim through it easier.

2021-08-24 13:31 UTC, koevskinikola commented on content/user-guide/quarkus-integration/configuration.md
> +### Programmatic Process Engine Configuration
Yeah, I think it makes sense. It also reduces the length of this headline.

2021-08-24 13:35 UTC, koevskinikola commented on content/user-guide/quarkus-integration/configuration.md
> +* The `idGenerator` is set to an instance of {{< javadocref page="?org/camunda/bpm/engine/impl/persistence/StrongUuidGenerator.html" text="StrongUuidGenerator" >}}.
Yup, I had my doubts as well. A table would look better.

2021-08-24 13:39 UTC, koevskinikola commented on content/user-guide/quarkus-integration/configuration.md
> +  }
It is simpler, but wouldn't it be better for the user to notice that the `@ApplicationScoped` class can produce other CDI beans as well?

2021-08-24 13:57 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +  }
I think it is not our goal to educate users subliminally about additional CDI functionality. From a user perspective, I find it easier to understand a code example if it is as simple as possible reduced to what really matters. Both examples are not super complex. So decide for yourself. I can live with both outcomes. 🙂

2021-08-24 13:59 UTC, tasso94 commented on content/user-guide/quarkus-integration/configuration.md
> +  }
One more thing, if you decide against my proposal: can we remove the `static` modifier and add `public` instead? Also, remove the indention?

2021-08-24 14:21 UTC, koevskinikola commented on content/user-guide/quarkus-integration/configuration.md
> +  }
It won't be a problem, I added your proposal :smile:

2021-08-24 15:03 UTC, merged