CAM-13838: document Quarkus compatibility
camunda/camunda-docs-manual pull request #1048
Opened 2021-08-23 15:52 UTC by koevskinikola

Related to CAM-13838

2021-08-24 14:40 UTC, tasso94 requested changes
Looks good to me in general. Please see some hints below:

2021-08-24 14:40 UTC, tasso94 commented on content/user-guide/quarkus-integration/_index.md
> +* executable JAR with embedded Tomcat and one embedded process engine.
```suggestion
* executable JAR with one embedded process engine.
```

2021-08-24 14:40 UTC, tasso94 commented on content/user-guide/quarkus-integration/version-compatibility.md
> +tested before being used in production.
```suggestion
Only these default combinations are recommended (and supported) by Camunda.
```
> Other combinations must be thoroughly tested before being used in production.

This sentence confuses me a bit. Who must test it? Is it me or Camunda? Should we remove this sentence entirely?

2021-08-24 14:40 UTC, tasso94 commented on content/user-guide/quarkus-integration/version-compatibility.md
> +In case a certain Quarkus version has a bug, users can override the existing Quarkus version by adding the following
```suggestion
In case a certain Quarkus version has a bug, you can override the existing Quarkus version by adding the following
```

2021-08-24 14:40 UTC, tasso94 commented on content/user-guide/quarkus-integration/version-compatibility.md
> +inside their `pom.xml`. Note that this new Camunda/Quarkus version combination should also be supported by Camunda.
```suggestion
inside your `pom.xml`. Note that this new Camunda/Quarkus version combination should also be supported by Camunda.
```

2021-08-24 15:07 UTC, koevskinikola commented on content/user-guide/quarkus-integration/version-compatibility.md
> +tested before being used in production.
I decided to leave this sentence from the Spring Boot docs, but I would be okay to remove it. It doesn't provide much value.

2021-08-25 11:57 UTC, tasso94 approved these changes

2021-08-25 12:08 UTC, merged