docs(user-guide): add CorrelateMessage batch operation
camunda/camunda-docs-manual pull request #1070
Opened 2021-09-03 14:08 UTC by tmetzke

* adds the CorrelateMessage batch operation to the list of operations
* adds the user operation log entry created by the CorrelateMessage batch

related to CAM-13863, CAM-13819

2021-09-08 08:32 UTC, tasso94 requested changes
Looks good to me in general. 

Just some hints at which other places in the docs we could mention the new batch operation as well:
* Should we add the new batch operation to the configuration map `batchOperationsForHistoryCleanup` [example](https://docs.camunda.org/manual/develop/user-guide/process-engine/history/#batches)?
* Should we link back to your documentation by adding the batch operation to [this list](https://docs.camunda.org/manual/develop/user-guide/process-engine/batch/#creating-a-batch)?
* Should we reflect the "create batch" permission [here](https://docs.camunda.org/manual/develop/user-guide/process-engine/authorization-service/#additional-batch-permissions)?

WDYT?

2021-09-08 08:49 UTC, tmetzke commented
> Should we add the new batch operation to the configuration map batchOperationsForHistoryCleanup example?

Yes, very good idea!  👍 
I assume we need to adjust the backend as well then to take it into consideration?

> Should we link back to your documentation by adding the batch operation to this list?

I didn't have a look at all the links in both lists (the one on the "Batch" page and the one on the "Batch operations" page), but how about we remove the list from the "Batch" page and reference to the "Batch operations" page instead? Is there a specific need to maintain the list twice?

> Should we reflect the "create batch" permission here?

Yes, definitely! 👍

2021-09-08 09:21 UTC, tasso94 commented
> Is there a specific need to maintain the list twice?

Fully agree with your proposal to reduce maintenance efforts.

> I assume we need to adjust the backend as well then to take it into consideration?

Should work out of the box.

2021-09-08 09:26 UTC, tmetzke commented
>> I assume we need to adjust the backend as well then to take it into consideration?

> Should work out of the box.

OK, found the code for that, very nice! 👍

2021-09-08 09:36 UTC, tmetzke commented on content/user-guide/process-engine/batch-operations.md
> +Execution jobs only contain elements of the same deployment and are bound to that deployment's id.
I didn't adjust anything here content-wise, just added newlines

2021-09-08 11:05 UTC, tasso94 commented
One more thing: should we link back to your documentation from the [Message API](https://docs.camunda.org/manual/develop/reference/bpmn20/events/message-events/#message-api) documentation?

2021-09-08 11:11 UTC, tmetzke commented
I thought about it but couldn't find a good place to add it, actually. Since it also works differently than the synchronous correlation (no message start events, other parameters, different filtering), I decided against it for now. 

Let me know if you think otherwise 🙂

2021-09-09 12:10 UTC, tasso94 approved these changes
Nice 🚀 💯

2021-09-13 09:38 UTC, merged