docs(update): task worker metrics config
camunda/camunda-docs-manual pull request #1114
Opened 2021-11-25 10:17 UTC by danielkelemen

* document the new task worker metrics behaviour and config

related to CAM-13640

2021-11-25 10:50 UTC, tasso94 requested changes
Looks good in general. 🙂 👍 

Once the technical review is done, let's assign `@christinaausley` for review as well.

I added some review hints below:

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/jboss.md
> +[update-guide]: {{< ref "/update/minor/715-to-716/_index.md" >}}
```suggestion
[update-guide]: {{< ref "/update/minor/716-to-717/_index.md" >}}
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/tomcat.md
> +[update-guide]: {{< ref "/update/minor/715-to-716/_index.md" >}}
```suggestion
[update-guide]: {{< ref "/update/minor/716-to-717/_index.md" >}}
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/was.md
> +[update-guide]: {{< ref "/update/minor/715-to-716/_index.md" >}}
```suggestion
[update-guide]: {{< ref "/update/minor/716-to-717/_index.md" >}}
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/wls.md
> +[update-guide]: {{< ref "/update/minor/715-to-716/_index.md" >}}
```suggestion
[update-guide]: {{< ref "/update/minor/716-to-717/_index.md" >}}
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/_index.md
> +   `targetDataSource`'s bean class to `com.zaxxer.hikari.HikariDataSource` and rename the `url` parameter of the data source to `jdbcUrl`.
```suggestion
   section.
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/_index.md
> +and batch variables might not be removed when an old engine executes the monitor job.
```suggestion
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/_index.md
> +1. For administrators: [Set Variables on Process Instance Migration](#set-variables-on-process-instance-migration)
```suggestion
1. For administrators: [Task Worker Metrics](#task-worker-metrics)
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/_index.md
> +Starting from version 7.17 the task worker metrics are displayed by default.
```suggestion
Starting from version 7.17, the task worker metrics are displayed by default.
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/_index.md
> +If this causes slow page loading you can turn it off in the  [admin webapp configuration.]({{< ref "/webapps/admin/configuration.md#task-worker-metrics" >}})
```suggestion
If this causes slow page loading, you can turn it off in the  [admin webapp configuration.]({{< ref "/webapps/admin/configuration.md#task-worker-metrics" >}})
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/jboss.md
> +title: "Update a JBoss/Wildfly Installation from 7.16 to 7.17"
```suggestion
title: "Update a JBoss EAP 6 or Wildfly / JBoss EAP 7 Installation from 7.16 to 7.17"
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/jboss.md
> +    name: "JBoss AS/Wildfly"
```suggestion
    name: "JBoss EAP 6 or Wildfly / JBoss EAP 7"
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/jboss.md
> +7 and Wildfly server in a shared process engine scenario. For the entire
```suggestion
The following steps describe how to update the Camunda artifacts on a JBoss EAP 6 or Wildfly / JBoss EAP 7 in a shared process engine scenario. For the entire
```

2021-11-25 10:50 UTC, tasso94 commented on content/update/minor/716-to-717/_index.md
> +* [JBoss AS/Wildfly]({{< ref "/update/minor/716-to-717/jboss.md" >}})
```suggestion
* [JBoss EAP 6 or Wildfly / JBoss EAP 7]({{< ref "/update/minor/716-to-717/jboss.md" >}})
```

2021-11-25 12:03 UTC, tasso94 approved these changes
Looks good to me. Let's request another review from @christinaausley.

2021-11-29 21:17 UTC, christinaausley approved these changes
Added a commit with my editorial/technical revisions -- looks great!

2021-12-06 08:41 UTC, merged