docs(intro): Update docs where redirects were not possible
camunda/camunda-docs-manual pull request #1140
Opened 2022-01-13 22:55 UTC by akeller

Closes [CAM-14286](https://jira.camunda.com/browse/CAM-14286).

2022-01-14 07:44 UTC, MaxTru requested changes
Why not deep link to the respective ressource? This could make the user experience smoother.

For example:

```
[Third-Party libraries](https://docs.camunda.io/docs/reference/dependencies/) for Camunda Modeler have moved to docs.camunda.io/CamundaModelerThirdPartyLibraries.
```

2022-01-14 07:44 UTC, MaxTru commented on content/introduction/licenses.md
> +[License information](https://docs.camunda.io/docs/reference/licenses/#camunda-modeler) for Camunda Modeler has moved to docs.camunda.io.
For all here: why not hyperlink?

```suggestion
[License information](https://docs.camunda.io/docs/reference/licenses/#camunda-modeler) for Camunda Modeler has moved to [docs.camunda.io](https://docs.camunda.io/).
```

2022-01-21 16:29 UTC, akeller commented
@MaxTru deep linking on tabs in Docusaurus doesn't appear to work at this time. I agree this would make the user experience smoother, but I think we would need to do some engineering here to make this work. I'll get this added into our backlog.

2022-01-24 07:11 UTC, MaxTru approved these changes

2022-01-24 07:11 UTC, merged