CAM-14285: document disabled remote access to h2 console
camunda/camunda-docs-manual pull request #1144
Opened 2022-01-28 16:36 UTC by ThorbenLindhauer

related to CAM-14285

2022-02-08 19:58 UTC, tmetzke requested changes
I like the pragmatic and concise description 👍 
I only added some grammatical suggestions.

2022-02-08 19:58 UTC, tmetzke commented on content/update/minor/716-to-717/_index.md
> +This set of patches deactivates remote access to the H2 console application in the Tomcat and Wildfly distributions. The H2 application accepts only localhost connections moving forward.
```suggestion
The Camunda Platform 7.17.0 release deactivates remote access to the H2 console application in the Tomcat and Wildfly distributions. The H2 application accepts only localhost connections moving forward.
```

2022-02-08 19:58 UTC, tmetzke commented on content/update/minor/716-to-717/_index.md
> +`web.xml` is located in the following paths:
```suggestion
You can find the `web.xml` at the following paths:
```

2022-02-08 19:58 UTC, tmetzke commented on content/update/patch-level.md
> +`web.xml` is located in the following paths:
```suggestion
You can find the `web.xml` at the following paths:
```

2022-02-09 12:42 UTC, tmetzke approved these changes

2022-02-09 15:21 UTC, christinaausley approved these changes
This looks great -- excellent work and no edits on my end.

Note that you can remove "please" from "please note" moving forward to keep things concise. You can just say "Note that we strongly discourage..."

By the way, I know we have :::note admonitions in Cloud, but do we have anything of the likes within Platform? Just curious.

2022-02-09 17:00 UTC, merged