CAM-13338: doc(run): add guide on how to add process engine plugins
camunda/camunda-docs-manual pull request #1148
Opened 2022-02-02 15:35 UTC by koevskinikola

Related to CAM-13338

2022-02-09 16:03 UTC, mboskamp requested changes
Very nice documentation!

I added a few comments regarding examples for plugins that can not be configured.
I think it would be great to have some resources for plugin creators on how to document their plugins for Run users. We have to keep in mind that they are not Java users and might not know how to identify an interface, for example.

2022-02-09 16:03 UTC, mboskamp commented on content/user-guide/camunda-bpm-run.md
> +  * Find the canonical name of the process engine plugin Java class that implements the `ProcessEnginePlugin` interface.
To non-Java users, it might not be clear how to identify that class. They might not know what a Java interface is. We should educate our plugin creators on how to provide the information so that Run users can understand them. Might be a nice idea to talk to dev-rel on that too.

2022-02-16 14:06 UTC, koevskinikola commented
@christinaausley the new docs that I am adding are intended for non-Java developers. If you have any additional hints regarding that type of documentation, please let me know. :slightly_smiling_face:

2022-02-17 16:23 UTC, christinaausley approved these changes
This is excellent. I made a few minor changes in my latest commit. I really liked how you outlined the first portion in steps, so I applied the same to the second portion of action items.

2022-02-21 11:06 UTC, merged