Improve form key
camunda/camunda-docs-manual pull request #1149
Opened 2022-02-08 17:43 UTC by ingorichtsmeier

First draft to prefer `formRef` over `formKey` for Camunda Forms

2022-02-08 21:01 UTC, smbea reviewed
I think the explanation is simple and clear, and it motivates users to use formRef as default. And it goes in line with https://github.com/bpmn-io/bpmn-js-properties-panel/pull/574. WDYT @MaxTru ?

2022-02-09 07:10 UTC, MaxTru commented
Makes sense!

2022-02-09 07:13 UTC, MaxTru requested changes
Just one small adjustment, then "ready to merge" from my perspective

2022-02-09 07:13 UTC, MaxTru commented on content/user-guide/task-forms/_index.md
> +With Form References, Camunda Forms provide a flexible way of linking an element in a BPMN diagram to a form. To link a BPMN element ([StartEvent][start-event] or [UserTask][user-tasks]) to a Camunda
```suggestion
With Form References, Camunda Forms provide a flexible way of linking an element in a BPMN diagram to a form. To link a BPMN element ([StartEvent][start-event] or [UserTask][user-tasks]) to a Camunda Form, you have to specify the Id of the Camunda Form as the `camunda:formRef` attribute. Additionally, the `camunda:formRefBinding` attribute specifies which version of the Camunda Form to reference.
```

2022-02-10 07:40 UTC, MaxTru approved these changes

2022-02-10 07:43 UTC, merged