docs(modeler): stub pages, point to new docs
camunda/camunda-docs-manual pull request #1150
Opened 2022-02-08 20:33 UTC by akeller

Completing Modeler docs content migration to docs.camunda.io. 

Related to [CAM-14335](https://jira.camunda.com/browse/CAM-14335).

2022-02-10 08:06 UTC, MaxTru requested changes
In multiple cases you put
```
(docs.camunda.io)[https://docs.camunda.io/] 
```

but you need to put
```
[docs.camunda.io]/https://docs.camunda.io/])
```

2022-02-10 08:06 UTC, MaxTru commented on content/introduction/licenses.md
> +[Third-Party libraries](https://docs.camunda.io/docs/reference/dependencies/) for Camunda Modeler have moved to [docs.camunda.io](https://docs.camunda.io/).
Why not deeplink to https://docs.camunda.io/docs/reference/dependencies/?

2022-02-10 08:06 UTC, MaxTru commented on content/modeler/_index.md
> +This content has moved to (docs.camunda.io)[https://docs.camunda.io/] and is available [here](https://docs.camunda.io/docs/components/modeler/about-modeler/) for all future versions.
```suggestion
This content has moved to [docs.camunda.io](https://docs.camunda.io/) and is available [here](https://docs.camunda.io/docs/components/modeler/about-modeler/) for all future versions.
```

2022-02-10 08:09 UTC, MaxTru commented on content/modeler/forms.md
> +This content has moved to (docs.camunda.io)[https://docs.camunda.io/] and is available [here](https://docs.camunda.io/docs/guides/utilizing-forms/) for all future versions.
The Forms Reference in the Cloud docs in not yet ready for Platform. E.g., there is no link to [Camunda Forms Reference]({{< ref "/reference/forms/camunda-forms/_index.md#configuration" >}}) which explains how to implement the linking. Will this be added?

2022-02-14 17:41 UTC, akeller commented on content/introduction/licenses.md
> +[Third-Party libraries](https://docs.camunda.io/docs/reference/dependencies/) for Camunda Modeler have moved to [docs.camunda.io](https://docs.camunda.io/).
For both links? I did on the first one but was adding the additional link to the overall docs.

2022-02-14 17:45 UTC, akeller commented on content/modeler/forms.md
> +This content has moved to (docs.camunda.io)[https://docs.camunda.io/] and is available [here](https://docs.camunda.io/docs/guides/utilizing-forms/) for all future versions.
I'm not sure I understand. Did this content not move to docs.camunda.io? Or am I referencing the wrong URL? If there is something that needs to be added to documentation content on docs.camunda.io can you create a PR or issue for that?

2022-02-16 11:14 UTC, MaxTru commented on content/modeler/forms.md
> +This content has moved to (docs.camunda.io)[https://docs.camunda.io/] and is available [here](https://docs.camunda.io/docs/guides/utilizing-forms/) for all future versions.
Sure, => https://github.com/camunda-cloud/camunda-cloud-documentation/issues/613

2022-02-16 12:22 UTC, MaxTru approved these changes

2022-03-18 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=1150) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=1150) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-manual?pullRequest=1150) it.</sub>

2022-03-18 08:33 UTC, MaxTru approved these changes

2022-03-18 15:36 UTC, akeller commented
I'm having trouble signing the CLA. Also, I wasn't sure who is supposed to merge this. Is it me? 😅

2022-03-18 15:38 UTC, MaxTru commented
> I'm having trouble signing the CLA. Also, I wasn't sure who is supposed to merge this. Is it me? sweat_smile

I think this should auto-merge once you signed the CLA (IT could help). Or you just manually merge? :-) :bomb:

2022-03-18 16:37 UTC, merged