CAM-14293: doc(run): document start/stop script changes
camunda/camunda-docs-manual pull request #1151
Opened 2022-02-15 14:08 UTC by koevskinikola

Related to CAM-14293

2022-02-16 07:32 UTC, tmetzke requested changes
I like the new section explaining the script parameters explicitly, that is a nice idea 👍 

I think it makes sense to explain the detached behavior a bit (what will happen when you simply execute the start scripts as is) and how it differs when an option is passed. That is not clear yet and might lead to confusion otherwise. You covered that a bit in the script parameters section. I think we can be a bit more explicit here. 🙂

2022-02-16 07:32 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +http://localhost:8080/engine-rest/ and Swagger UI via http://localhost:8080/swaggerui/.
```suggestion
http://localhost:8080/engine-rest/, and Swagger UI via http://localhost:8080/swaggerui/.
```

2022-02-16 07:32 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +Execute one of the two start scripts (`start.bat` for Windows, `start.sh` for Linux/Mac). After a few seconds, you will
```suggestion
Execute one of the two start scripts (`start.bat` for Windows, `start.sh` for Linux/Mac). After a few seconds, you can
```

2022-02-16 07:32 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +be able to access the Camunda webapps via http://localhost:8080/camunda/app/, the REST API via
```suggestion
access the Camunda webapps via http://localhost:8080/camunda/app/, the REST API via 
```

2022-02-16 07:32 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +(`shutdown.bat` for Windows, `shutdown.sh` for Linux/Mac).
I think it makes more sense to incorporate this information into the previous paragraph where the start behavior is explained. You can then refer to the detached start as the scenario where using the shutdown scripts makes sense (and only works there).

2022-02-16 07:32 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +
Let's add a paragraph on explaining detached default behavior and how that changes when additional arguments are passed on.

2022-02-16 10:23 UTC, mboskamp requested changes

2022-02-16 10:23 UTC, mboskamp commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
Let's add the `--help` argument to that list.

2022-02-16 10:48 UTC, koevskinikola commented on content/user-guide/camunda-bpm-run.md
> +http://localhost:8080/engine-rest/ and Swagger UI via http://localhost:8080/swaggerui/.
Isn't this the Oxford comma case?

2022-02-16 10:50 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +http://localhost:8080/engine-rest/ and Swagger UI via http://localhost:8080/swaggerui/.
I believe so, yes. This means we always add the comma for clarity for lists with more than 2 items, don't we?

2022-02-16 10:54 UTC, koevskinikola commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
The thing is, the `help` argument is part of the `run.sh|bat` arguments. It's on the same level as `run.sh start` and `run.sh stop`. So calling `start.sh --help` won't do anything. Do you think I should refactor the scripts?

2022-02-16 10:56 UTC, mboskamp commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
Is that intended behavior? I think it would be nice to have that option for the `start` scripts. Not sure if anybody will ever use it if we hide it in the `run` scripts.
See also my comment in the platform PR.

2022-02-16 10:59 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
So users could run `start.bat help`, right? And we then pass this on to the run script accordingly. How about that?

2022-02-16 11:03 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
I think this just needs to change in the `start.sh|bat`. It can pass on the request for help accordingly. No matter if we want it to be `start.sh help` or `start.sh --help`.

2022-02-16 11:06 UTC, mboskamp commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
I think we already pass it to the `run` script. We just don't react to it if it comes from the `start` script (If I am not mistaken). My suggestion in the platform PR for the `bat` works for me. I could call `start.bat --help` and see the output of the `:Help` section.

I thought this was the intended behavior. If there is any reason not to do it, I am completely open for that :D

2022-02-16 11:08 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
Maybe we can have a look at what is typical for command lines on Unix and Windows in order get help for a command. I believe on Linux it's `<cmd> --help` or `<cmd> -h`? On Windows, you can usually do something like `<cmd> -help` or `<cmd> /?`.

2022-02-16 11:10 UTC, tmetzke commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
@mboskamp, with a config parameter, we maybe have to consider what happens if people call `start --rest --help` for example?

2022-02-16 11:44 UTC, koevskinikola commented on content/user-guide/camunda-bpm-run.md
> +http://localhost:8080/engine-rest/ and Swagger UI via http://localhost:8080/swaggerui/.
Agh, sorry about that. I mixed up the GitHub UI `+/-` lines. Fixed it.

2022-02-16 12:47 UTC, koevskinikola commented on content/user-guide/camunda-bpm-run.md
> +  </tr>
See https://github.com/camunda/camunda-bpm-platform/pull/1745#discussion_r807916088.

2022-02-16 13:35 UTC, tmetzke approved these changes
Really nice 👍

2022-02-17 13:43 UTC, mboskamp approved these changes

2022-02-17 18:51 UTC, christinaausley approved these changes
Very minor adjustments in latest commit.

2022-02-22 14:09 UTC, merged