docs(admin): document diagnostics feature
camunda/camunda-docs-manual pull request #1180
Opened 2022-03-17 13:24 UTC by cliftondavies

related to CAM-14449

2022-03-18 09:26 UTC, tasso94 requested changes
Please see my review hint below:

2022-03-18 09:26 UTC, tasso94 commented on content/webapps/admin/system-management.md
> +The Diagnostics menu allows you to view and copy telemetry data about your environment or distribution of Camunda. The aim is to improve problem diagnosis by ensuring our customer facing departments
Similar feedback that I already gave on the translation string. 

The primary product management motivation to invest in that topic is that our customer-facing departments can request this information from users. However, this shouldn't be so much of an interest for all of our users (especially not for our community users who don't have direct access to our support services). The feature might also help us do community work or in the forum.

Can you generalize more about how a user can benefit from this feature? I think we should especially remove the term `customer facing departments`. 

The backend documentation that already exists might help you as well: https://docs.camunda.org/manual/develop/reference/rest/telemetry/get-telemetry-data/.

2022-03-22 09:41 UTC, tasso94 approved these changes
I really like how you incorporated my feedback! Reads very nice now. 🙂 👍 

Going forward please request a technical writing review from `@christinaausley`.

2022-03-22 17:51 UTC, christinaausley approved these changes
Bolded the section name in latest commit, as all UX components referenced are to be bolded. LGTM otherwise!

2022-03-23 08:48 UTC, merged