docs(csp): update content security policy
camunda/camunda-docs-manual pull request #1220
Opened 2022-05-03 16:02 UTC by danielkelemen

related to CAM-14139

2022-05-12 12:08 UTC, tasso94 commented on content/update/minor/717-to-718/_index.md
> +In older versions the default policy used to be a very minimal configuration, allowing almost everything.\
```suggestion
In older versions, the default policy used to be a very minimal configuration, which had to be intentionally strengthened according to our recommendations.\
```

2022-05-13 15:35 UTC, tasso94 requested changes
Looks good to me in general. However, please find below some review hints ⬇️

2022-05-16 13:19 UTC, danielkelemen commented on content/webapps/shared-options/header-security.md
> +  * The `$NONCE` placeholder is replaced with a random generated string by the engine, it can be used to enable inline scripts
Okay, makes sense.
I will also add some info about the index placeholder ($CSP_NONCE).

2022-05-18 10:02 UTC, tasso94 approved these changes

2022-05-20 12:16 UTC, merged