docs(process-engine): config property for bpmn stacktrace log level
camunda/camunda-docs-manual pull request #1247
Opened 2022-06-02 13:33 UTC by danielkelemen

related to CAM-13977

2022-06-03 07:39 UTC, koevskinikola requested changes
Looks good. I only have two suggestions:
1. Should we reference the property in the logging section here: https://github.com/camunda/camunda-docs-manual/blob/master/content/user-guide/logging.md#logging-categories?
2. Should we expand the update section to explain to users what they need or needn't do for this change?

2022-06-03 07:39 UTC, koevskinikola commented on content/update/minor/717-to-718/_index.md
> +See the [Logging level parameters]({{< ref "/reference/deployment-descriptors/tags/process-engine.md#logLevelBpmnStackTrace" >}}) section for details.
Should we also describe what the impact is? For example, tell users that the previous default remains and that they don't need to do any adjustments.

2022-06-03 13:16 UTC, danielkelemen commented on content/update/minor/717-to-718/_index.md
> +See the [Logging level parameters]({{< ref "/reference/deployment-descriptors/tags/process-engine.md#logLevelBpmnStackTrace" >}}) section for details.
Good points!
I added some extra infos about the impact and what they could do.
I also referenced the new parameters in the logging user-guide.
Let me know what you think!

2022-06-07 06:25 UTC, koevskinikola approved these changes

2022-06-07 06:25 UTC, koevskinikola commented on content/update/minor/717-to-718/_index.md
> +See the [Logging level parameters]({{< ref "/reference/deployment-descriptors/tags/process-engine.md#logLevelBpmnStackTrace" >}}) section for details.
Looks great!

2022-06-07 08:44 UTC, merged