docs(batch): add batch startTime to API
camunda/camunda-docs-manual pull request #1266
Opened 2022-07-12 15:42 UTC by danielkelemen

related to CAM-14721

2022-07-19 07:51 UTC, ThorbenLindhauer requested changes
It looks like you updated the wrong endpoint description, please check the comment.

2022-07-19 07:51 UTC, ThorbenLindhauer commented on content/reference/rest/batch/get-query.md
> +      Valid values are <code>batchId</code>, <code>tenantId</code> and <code>startTime</code>.
This and the result property should go to `get-statistics-query.md`.

2022-08-03 13:09 UTC, danielkelemen commented on content/reference/rest/batch/get-query.md
> +      Valid values are <code>batchId</code>, <code>tenantId</code> and <code>startTime</code>.
You're right, the new sortBy property is only available for the statistics query.
What did you mean by the result property? The new startTime field is returned for both batch and statistics endpoints.

2022-08-04 15:01 UTC, ThorbenLindhauer commented on content/reference/rest/batch/get-query.md
> +      Valid values are <code>batchId</code>, <code>tenantId</code> and <code>startTime</code>.
Yeah, you are right. I don't recall why I wrote it like that.

2022-08-04 15:02 UTC, ThorbenLindhauer approved these changes
Looks good!

2022-08-04 15:52 UTC, merged