docs(chore): Update Community Extensions page
camunda/camunda-docs-manual pull request #1275
Opened 2022-08-08 21:43 UTC by xomiamoore

Small edits for current links and moving contributing to the core product to its own section.

2022-08-11 17:06 UTC, akeller commented
Before I review this, @xomiamoore, the C7 docs (this repo) has a number of different branches, including branches per version. I believe `master` still corresponds with `latest` so your change, when pushed live, would only be available on `latest` and future versions. If this is in line with your expectations, then great! If not, or you still have questions, I recommend working with @christinaausley or an engineer who is working in the C7 docs regularly.

2022-08-11 17:11 UTC, akeller requested changes
Left a comment!

Additionally you may want to look at the docs.camunda.org homepage - scroll to the bottom there is a brief community section with links a well.

2022-08-11 17:11 UTC, akeller commented on content/introduction/extensions.md
> +Camunda Platform is developed by Camunda as an open source project in collaboration with the community. The "core project" (namely "Camunda Platform") is the basis for the Camunda Platform product wh
The previous link for the product page definitely 404s, but I'm not sure if the Platform page is the right one since it's so C8-focused. Could you check in with ask-marketing? I would also update the text for this link to say "Camunda Platform 7 product".

Regarding the bug fix releases link, relative links should work, but double check that it's working on the live page 😄

2022-08-12 17:06 UTC, xomiamoore commented on content/introduction/extensions.md
> +Camunda Platform is developed by Camunda as an open source project in collaboration with the community. The "core project" (namely "Camunda Platform") is the basis for the Camunda Platform product wh
Fixed! I didn't realize that link was only Camunda 8, gotta read more carefully 😂

2022-08-12 17:07 UTC, xomiamoore commented
@christinaausley, there are a few places where the wording is a bit awkward in the first paragraph with product names, would love your eyes on this when you get a chance!

2022-08-12 17:34 UTC, xomiamoore commented on layouts/index.html
> -          you want to hack on Camunda itself or want to understand the inner workings.</p>
This link no longer works and I couldn't find a "Developer's Guide" anywhere, so I deleted this.

2022-08-12 17:59 UTC, akeller commented on layouts/index.html
> -          you want to hack on Camunda itself or want to understand the inner workings.</p>
![image](https://user-images.githubusercontent.com/1051363/184416275-4ca57b07-76b8-4736-91c0-cd092c842f7c.png)

I haven't dug into this content. Can you connect with the C7 team to see if this is the best resource?

2022-08-12 19:30 UTC, xomiamoore commented on layouts/index.html
> -          you want to hack on Camunda itself or want to understand the inner workings.</p>
I asked, I don't expect an answer til Monday :)

2022-08-12 20:16 UTC, christinaausley commented on content/introduction/extensions.md
> +Camunda Platform is developed by Camunda as an open source project in collaboration with the community. The "core project" (namely "Camunda Platform") is the basis for the Camunda Platform product wh
Maybe...
"Camunda Platform is developed by Camunda as an open source project in collaboration with the community. This is the basis for the Camunda Platform product provided by Camunda as a commercial offering.

The commercial [Camunda Platform 7 product](https://camunda.com/platform-7/) contains additional (non-open source) features and is provided to Camunda Platform customers with service offerings such as enterprise support and [bug fix releases](/enterprise/download/)."

2022-08-15 15:45 UTC, xomiamoore commented on layouts/index.html
> -          you want to hack on Camunda itself or want to understand the inner workings.</p>
Thorben says delete it!

2022-08-17 19:40 UTC, christinaausley approved these changes
Nice changes here!

2022-08-17 20:59 UTC, merged