CAM-14742: add liberty installation docs
camunda/camunda-docs-manual pull request #1282
Opened 2022-08-24 15:15 UTC by koevskinikola

Related to CAM-14742

2022-09-09 15:27 UTC, ThorbenLindhauer requested changes
I'll begin my review by sharing my installation experience going through the guide. Further down below and in the diff I will give concrete review hints.

# Experience

My prior knowledge: No hands-on experience; high-level conceptual understanding of WAS Liberty based on our syncs

I downloaded WAS Liberty from here: https://www.ibm.com/support/pages/node/6250961. I wasn't sure which edition to choose, then opted for `WebSphere Liberty Jakarta EE 8 22.0.0.9` as the guide mentions Java EE 8 compatibility.

I didn't know how to set up a server (later I saw that the WAS Liberty docs have some guidance on this). I decided to create the necessary files from hand as I follow the guide. I wasn't sure if this was a good approach, but it turned out okay in the end. It was good to have an overview at the beginning of the guide of what we want to create. 

Following the sections of the guide, I copied over files from the WAS9 distribution and edited `server.xml` as I went along, copying the example code.

Problems that I faced and resolved outside of the guide:

* The example XML snippets do not contain the version number (or placeholder) for the artifact names (e.g. the path to the EAR). I noticed that as I was working through the guide.
* The first start logged warnings that some of the features were not installed yet. I installed them by running `.\installUtility install camundaServer` on the command line as instructed by the log file.
* I didn't define the elements `httpEndpoint`, `applicationManager`, and `ssl` at first. I noticed them only later when I went back to the top of the guide and added them.

Problems I couldn't resolve yet:

* I installed the invoice example following the instructions for process applications. It looks like this WAR is deployed before or in parallel with the EAR. Accordingly it doesn't find a process engine yet.
* I defined a H2 datasource. Liberty cannot initialize it complaining about a `java.lang.ClassNotFoundException: com.ibm.websphere.rsadapter.GenericDataStoreHelper`. From quick research, this should come with `heritageAPIs-1.1`. I am confused why this doesn't work and couldn't help myself from a brief google search.

As a result, I didn't manage to install Camunda successfully. It would be great if we could have a look at this together next week.

Note, I am a complete WAS Liberty noob (with decent application server and Java knowledge though), so I may not be the target audience for the guide. See the next section on this.

# General review feedback

## Introduction

I liked a lot that the guide describes the target state at the beginning. It helped me make sure I am on track.

## Target audience

The target audience is not clear to me. Who do we want to be able to install Camunda successfully with this guide? Options:

* Any person with basic Java/Application server knowledge, but no clue about WAS Liberty
* People who have a fresh WAS Liberty installed (but may otherwise be newbies)
* People who have a WAS Liberty installed and a server already created (but may otherwise be newbies)
* People who have a WAS Liberty installed, a server already created, and know how to install and add features (but may otherwise be newbies)
* People who are WAS experts

I think it would help the audience a lot if we clarify this at the beginning of the guide and maybe even give some hints how to close the gap if the reader does not qualify (e.g. link to the WAS Liberty download page if the guide requires that the user has already downloaded it).

It could also help us decide what content should be in this guide and what not.

## Page structure

I think it would be better to separate the WAS 9 and Liberty guide into two separate pages. Except for two environment variables and the download artifact, they have nothing in common. For Liberty readers, it may be a bit cumbersome to scroll back to the top when they want to check the environment variables again.

2022-09-09 15:27 UTC, ThorbenLindhauer commented on content/installation/full/was/configuration.md
> +### WebSphere Liberty configuration
Couldn't try out this section yet as I didn't manage to get the installation running. This is a reminder for myself to check it later.

2022-09-09 15:27 UTC, ThorbenLindhauer commented on content/installation/full/was/manual.md
> +* `$SERVER_CONFIG_DIR` points to the IBM WebSphere Liberty server configuration directory like `wlp/usr/servers/camundaServer`.
Beginning to read this guide from the top, this list can be a bit confusing if I am only interested in one of the servers, because not all variables matter for both servers (e.g. `WAS_HOME` is not relevant for Liberty). As already shared in the general feedback, I think separating the guides into two pages would be better.

2022-09-12 06:36 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +                         location="${server.config.dir}/apps/camunda-ibm-websphere-ear.ear" >
That's a good idea. I was using the configuration from our QA module. There, I configured the Liberty maven plugin to strip any versions from the artifacts, to make it easier to maintain. I'll add placeholders here.

2022-09-12 06:37 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +      <td>Specifies the desired maximum number of threads that are used for alarms. The default value is 2.</td>
Woops, that's wrong. I copied over the description for the previous WAS9 property. I'll change it.

2022-09-12 06:40 UTC, koevskinikola commented on content/installation/full/was/manual.md
>  The distribution is available at the [Camunda enterprise release page](https://downloads.camunda.cloud/enterprise-release/camunda-bpm/ibm-was/).
I'll piggyback the fix on this PR.

2022-09-12 07:34 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +with the `bells-1.0` Liberty feature as described in the [Camunda shared library section](#camunda-shared-library).
Good point, I'll remove it.

2022-09-12 08:44 UTC, ThorbenLindhauer commented on content/installation/full/was/manual.md
> +               location="${server.config.dir}/apps/camunda-process-application.ear" >
Should we add `startAfterRef="camundaBpmPlatform"` here?

2022-09-12 09:10 UTC, tasso94 commented on content/installation/full/was/manual.md
> +                         location="${server.config.dir}/apps/camunda-ibm-websphere-ear.ear" >
Can we use the `minor-version` hugo short code instead of a generic placeholder?

2022-09-12 09:16 UTC, tasso94 commented on content/installation/full/was/manual.md
> +      isolationLevel="TRANSACTION_READ_COMMITTED" >
```suggestion
      isolationLevel="TRANSACTION_READ_COMMITTED" />
```

2022-09-12 12:33 UTC, tasso94 commented on content/installation/full/was/manual.md
> +                         location="${server.config.dir}apps/camunda-ibm-websphere-ear.ear" >
```suggestion
                         location="${server.config.dir}/apps/camunda-ibm-websphere-ear.ear" >
```

2022-09-12 13:38 UTC, tasso94 commented on content/installation/full/was/manual.md
> +    <fileset dir="${server.config.dir}/lib" includes="ojdbc8-*.jar" />
Here the Oracle JDBC driver is referenced, while below in the datasource config the DB2 data source class is used.

2022-09-12 20:32 UTC, christinaausley commented on content/installation/full/was/manual.md
> +* Create the database schema and tables
Are these steps to complete in sequential order? If so, I would make this a numerical list.

2022-09-12 20:32 UTC, christinaausley commented on content/installation/full/was/manual.md
> +* Create a database schema for the Camunda Platform yourself.
Same comment here.

2022-09-12 20:34 UTC, christinaausley commented on content/installation/full/was/manual.md
> +If this code is executed within a Camunda Platform 7 Job, the job is marked as failed, and can be retried.
Is Job meant to be capitalized here?

2022-09-12 20:40 UTC, christinaausley approved these changes
Very minor technical adjustments made in my latest commit. A few comments for clarification, but nothing that is blocking.

2022-09-13 07:30 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +2. Add the `jdbc-4.2` and `jndi-1.0` Liberty features to the `server.xml`
I added some sentences on prerequisite knowledge for creating a Liberty server and deploying applications in Liberty. Coupled with the "Server configuration" section, I think it should be enough.

2022-09-13 07:30 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +`$WAS_HOME\modules\camunda-ibm-websphere-ear-$VERSION.ear\camunda-ibm-websphere-service.jar\META-INF\` folder.
I moved the shared libs and EAR section to be first.

2022-09-13 07:42 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +If this code is executed within a Camunda Platform 7 Job, the job is marked as failed, and can be retried.
Yup, I'll correct it. Thanks!

2022-09-13 07:49 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +    <fileset dir="${server.config.dir}/lib" includes="ojdbc8-*.jar" />
I'll make it consistent by using DB2 only.

2022-09-13 07:52 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +        password="${database.password}" />
I'll refactor it, but I'll keep the `camundaJDBCLib` referrence to make the guide more readable.

2022-09-13 07:58 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +    <concurrencyPolicy max="4" maxQueueSize="5" maxPolicy="strict" runIfQueueFull="false" />
These values are mapped to the same ones from the WAS9 guide. I used the table [here](https://www.ibm.com/docs/en/was-liberty/nd?topic=mal-migrating-applications-that-use-concurrency-asynchronous-programming-models-liberty#d198264e161) to map them.

The webapp and engine IT tests have been running with this configuration without issues. So I think they are good default values.

2022-09-13 08:22 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +{{< /note >}}
I will move this to the [JTA Transaction integration](https://docs.camunda.org/manual/latest/user-guide/cdi-java-ee-integration/jta-transaction-integration/) page.

2022-09-13 08:52 UTC, koevskinikola commented on content/installation/full/was/manual.md
> +      isolationLevel="TRANSACTION_READ_COMMITTED" >
The `jdbcDriver` tag is supposed to be seld-closing. The same strange syntax highlighting happens in other places as well. 

I'm not really sure why the issue occurs.

2022-09-13 11:19 UTC, ThorbenLindhauer commented on content/installation/full/was/manual-liberty.md
> +* `$WAS_DISTRIBUTION` represents the downloaded Camunda Platform distribution for the IBM WebSphere Application Server, e.g., `camunda-ee-ibm-was-$PLATFORM_VERSION.zip`.
Here we should also have `was9` in the zip file name, right?

2022-09-13 11:26 UTC, ThorbenLindhauer commented on content/installation/full/was/manual-liberty.md
> +approach and not the **"embedded"** process engine one (aka self-contained Process Application).
This might confuse people. The entire guide is about installing a shared engine (and components for it), so I'd say it's fair to assume that the user knows this at this point.

2022-09-13 11:38 UTC, koevskinikola commented on content/installation/full/was/manual-liberty.md
> +* `$WAS_DISTRIBUTION` represents the downloaded Camunda Platform distribution for the IBM WebSphere Application Server, e.g., `camunda-ee-ibm-was-$PLATFORM_VERSION.zip`.
Yup, I corrected it.

2022-09-13 11:40 UTC, koevskinikola commented on content/installation/full/was/manual-liberty.md
> +                         location="${server.config.dir}/apps/camunda-ibm-websphere-ear-$PLATFORM_VERSION.ear" >
I missed it. That's a good idea. I'll update the guide.

2022-09-13 11:50 UTC, ThorbenLindhauer requested changes
Looks like there is a search and replace mistake now.

2022-09-13 11:50 UTC, ThorbenLindhauer commented on content/installation/full/was/manual-liberty.md
> +* `{{< minor-version >}}.0-ee` denotes the version of the Camunda Platform you want to install or already have installed, e.g., `7.15.6-ee`.
Here, the macro `{{< minor-version >}}` shouldn't be used. Do we still need this environment variable anyway?

2022-09-13 11:50 UTC, ThorbenLindhauer commented on content/installation/full/was/manual-liberty.md
> +* `{{< minor-version >}}.0-ee` denotes the version of the Camunda Platform you want to install or already have installed, e.g., `7.15.6-ee`.
You could also add a hint that the guide refers to `{{< minor-version >}}.0` and that the user should replace the version if they are installing a patch.

2022-09-13 11:52 UTC, koevskinikola commented on content/installation/full/was/manual-liberty.md
> +* `{{< minor-version >}}.0-ee` denotes the version of the Camunda Platform you want to install or already have installed, e.g., `7.15.6-ee`.
Good catch, I missed it.

2022-09-13 11:56 UTC, koevskinikola commented on content/installation/full/was/manual-liberty.md
> +* `{{< minor-version >}}.0-ee` denotes the version of the Camunda Platform you want to install or already have installed, e.g., `7.15.6-ee`.
I removed that environment variable, and added a separate paragraph informing users that install patch versions.

2022-09-13 13:17 UTC, ThorbenLindhauer approved these changes
Looks good, thank you!

2022-09-13 13:22 UTC, merged