docs(batch-operations): improve documentation for "Set a Removal Time"
camunda/camunda-docs-manual pull request #1324
Opened 2022-10-14 13:23 UTC by valeriaportolesicamunda

2022-10-14 13:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=1324) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=1324) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-manual?pullRequest=1324) it.</sub>

2022-10-17 07:06 UTC, yanavasileva commented
Related to https://github.com/camunda/camunda-bpm-platform/issues/2792

2022-10-17 07:08 UTC, yanavasileva commented
@valeriaportolesicamunda please note the changes should be reviewed by Automation Platform team (owner of the repo).

2022-10-17 07:19 UTC, garima-camunda commented
Thanks @yanavasileva . I have removed my name from the Reviewer list. Feel free to continue.

@valeriaportolesicamunda, we can discuss the process separately.

2022-10-17 07:22 UTC, yanavasileva commented
@garima-camunda, you can also add your input as reviewer.
@valeriaportolesicamunda please let me know the PR is ready and I can pick it up for a review on our side.

2022-10-17 07:34 UTC, valeriaportolesicamunda commented
@yanavasileva I confirm PR is ready

2022-10-21 07:39 UTC, yanavasileva requested changes
@valeriaportolesicamunda I suggested small changes about the style and wording.

In case you want to check by yourself, how the end documentation will look like, you need to [install Hugo](https://github.com/camunda/camunda-docs-manual#installing-hugo) and [build the project](https://github.com/camunda/camunda-docs-manual#building-the-documentation) with it.

2022-10-21 07:39 UTC, yanavasileva commented on content/user-guide/process-engine/batch-operations.md
> +Setting removal time to running process instances would delete data from historic tables (i.e. tables starting from ACT_HI_), but not from runtime tables (i.e. tables starting from ACT_RU_).
`_XXX_` is the markdown for italic style, so you can use single quotes in this situation to display the text. Also, I suggest emphasizing that we talk about _database_ tables.
```suggestion
Setting removal time to running process instances would delete data from historic database tables (i.e. tables starting from `ACT_HI_*`), but not from runtime database tables (i.e. tables starting from `ACT_RU_*`).
```

2022-10-28 08:20 UTC, yanavasileva commented
Applied the requested changes, adjusted the commit message and merged with 8eec91c.

2022-10-28 08:20 UTC, closed without merging