docs(history): improve documentation for history Removal-Time Strategy
camunda/camunda-docs-manual pull request #1327
Opened 2022-11-03 12:14 UTC by Nishant-sehgal

related to camunda/camunda-bpm-platform/issues/2829

2022-11-03 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=1327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=1327) before we can accept your contribution.<br/><hr/>**Nishant Sehgal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-manual?pullRequest=1327) it.</sub>

2022-11-04 07:26 UTC, mboskamp requested changes
Hi @Nishant-sehgal,
Thank you very much for picking up camunda/camunda-bpm-platform#2829 and working on it!
I think it would be good to give a bit more background information. The user wants to know what to look out for when using `historyRemovalTimeStrategy=start`.

Here is a bit of information from the ticket where this issue was brought up. Maybe you can use it to make the added documentation even more helpful:

* When you access the Cleanup Console, you can see a list of versioned process definitions but only if they have, at least, one finished instance. If no instance is finished, for a given process definition (version), you will not see anything about this process definition/version. So I thought that only finished instances are cleanable.
* If you perform a batch operation setting the removal time, without specifying to operate only on finished instances, you will modify that time even to unfinished instances, and you may have an odd situation in which the cleanable instances are more than the finished ones.
* If you then launch the Clean Up process, all the cleanable instances will be wiped from the History Tables (finished or not).
* So, when someone works on the unfinished instances, and they finish, you will never have a History for them (they seem to go on without any error)

2022-11-04 07:26 UTC, mboskamp commented on content/user-guide/process-engine/history.md
> +Note: With "historyRemovalTimeStrategy" set to "start", it is possible to delete historic data of running process instances.
```suggestion
Note: With `historyRemovalTimeStrategy` set to `start`, it is possible to delete historic data of running process instances.
```

2022-11-05 06:23 UTC, Nishant-sehgal commented
> Hi @Nishant-sehgal, Thank you very much for picking up [camunda/camunda-bpm-platform#2829](https://github.com/camunda/camunda-bpm-platform/issues/2829) and working on it! I think it would be good to give a bit more background information. The user wants to know what to look out for when using `historyRemovalTimeStrategy=start`.
> 
> Here is a bit of information from the ticket where this issue was brought up. Maybe you can use it to make the added documentation even more helpful:
> 
>     * When you access the Cleanup Console, you can see a list of versioned process definitions but only if they have, at least, one finished instance. If no instance is finished, for a given process definition (version), you will not see anything about this process definition/version. So I thought that only finished instances are cleanable.
> 
>     * If you perform a batch operation setting the removal time, without specifying to operate only on finished instances, you will modify that time even to unfinished instances, and you may have an odd situation in which the cleanable instances are more than the finished ones.
> 
>     * If you then launch the Clean Up process, all the cleanable instances will be wiped from the History Tables (finished or not).
> 
>     * So, when someone works on the unfinished instances, and they finish, you will never have a History for them (they seem to go on without any error)

Thanks for sharing the details.

The details you shared are specifically if some one use the cockpit to set the removal time which is different i believe because there is no historyRemovalTimeStrategy coming in picture.

What i have understood so far is `historyRemovalTimeStrategy= start` means whenever a process is started removal time will be calculated(start+ttl) and will be set for the involved entities.As soon as removal time is reached it gets cleaned up irrespective of process is running or finished.

Let me know shall i add more details or the info that is added is enough.

2022-11-09 05:09 UTC, Nishant-sehgal commented
@mboskamp Can you check if it looks good ?

2022-11-09 07:33 UTC, mboskamp requested changes
Hi @Nishant-sehgal, 
Thank you for going over the paragraph again. Now it is much better in my opinion.
I added some suggestions on how we can further improve the section. Could you please have a look and let me know if the changes work for you?
Cheers,
Miklas

2022-11-09 07:33 UTC, mboskamp commented on content/user-guide/process-engine/history.md
> +**Note:**: With `historyRemovalTimeStrategy` set to `start`, it is possible to delete historic data of running process instances.So whenever a process is started removal time will be calculated(start
```suggestion
**Note:**: With `historyRemovalTimeStrategy` set to `start`, it is possible to delete historic data of running process instances. When a process is started the removal time will be calculated (start+TTL) and will be set for all the activities of the process. As soon as removal time is reached data from historic tables gets cleaned up irrespective of whether the instance is running or completed. This may lead to the removal of the historic data before the process instance is finished resulting in no available history in Cockpit or history tables. A mitigation strategy is to choose a longer TTL value or set `historyRemovalTimeStrategy` to `end`.
```

2022-11-10 13:45 UTC, mboskamp approved these changes

2022-11-10 13:46 UTC, merged