chore(rest): introduce restref shortcode
camunda/camunda-docs-manual pull request #1344
Opened 2022-11-11 11:55 UTC by mboskamp

related to camunda/camunda-bpm-platform#2876

2022-11-15 16:32 UTC, tasso94 requested changes
Great job! Looks good to me in general. Just some hints added below ⬇️

2022-11-15 16:32 UTC, tasso94 commented on content/reference/rest/specification.md
> +---
```suggestion
---

On production, this should redirect to the following page: 

* https://stage.docs.camunda.org/rest/camunda-bpm-platform/{{< minor-version >}}/

Or to this page in case you are viewing the docs of the `master` or `latest` branch:

* https://stage.docs.camunda.org/rest/camunda-bpm-platform/{{< minor-version >}}-SNAPSHOT/

```
Let's give some context in case a developer stumbles upon this page.

2022-11-16 09:31 UTC, mboskamp commented on content/reference/rest/specification.md
> +---
Good point, I think we should also add it to the [javadoc](https://github.com/camunda/camunda-docs-manual/blob/master/content/reference/javadoc.md) page.

2022-11-16 09:42 UTC, mboskamp commented on content/reference/rest/specification.md
> +    name: "Specification"
Now thinking about it a bit more, doesn't the arrow usually indicate that a link opens in a new tab? Also, I think that would be the better behavior here since there is no real way to get back to the camunda docs from the REST documentation. The same applies to the Javadocs link. Both are currently opening in the same tab.

2022-11-16 09:44 UTC, mboskamp commented on content/reference/rest/specification.md
> +---
Is there a reason why you chose the stage version of the docs for the link?

2022-11-16 13:01 UTC, tasso94 commented on content/reference/rest/specification.md
> +    name: "Specification"
The usual pattern is that an arrow-up icon indicates an external link. Opening it in a new tab is an implementation detail of that pattern. Cf. behavior of Wikipedia for instance: 
![image](https://user-images.githubusercontent.com/3015690/202187404-c3bf9d00-9da4-46cd-8250-5e0fc6cd69c3.png)

How can we technically achieve that the page opens in a new tab? With the arrow icon, a user can at least use right-click or a shortcut to open the page in a new tab.

2022-11-16 13:02 UTC, tasso94 commented on content/reference/rest/specification.md
> +---
No.

2022-11-16 13:34 UTC, tasso94 commented on content/reference/rest/specification.md
> +    name: "Specification"
I agree. 🙂👍

2022-12-12 14:26 UTC, merged