docs(wildfly): document wildfly 27 and jakarta support
camunda/camunda-docs-manual pull request #1424
Opened 2023-03-21 07:53 UTC by tasso94

related to camunda/camunda-bpm-platform#3101

2023-03-21 09:46 UTC, tmetzke requested changes
👍 Love the adjustments.
I add a couple of 🔧 suggestions and ❓ questions where I saw fit. Nothing major in my regard, the overall changes look really good already! 🙂

2023-03-21 09:46 UTC, tmetzke commented on content/installation/full/jboss/manual.md
> +<server xmlns="urn:jboss:domain:20.0">
👍 Nice catch!

2023-03-21 09:46 UTC, tmetzke commented on content/installation/full/jboss/manual.md
> +This section describes how to install optional dependencies. None of these are required to work with the core platform. Before continuing, make sure that the Camunda Platform is already installed acc
🔧 If we adjust the required setup section name, we need to adjust it here as well.
```suggestion
This section describes how to install optional dependencies. None of these are required to work with the core platform. Before continuing, make sure that the Camunda Platform is already installed according to [this step]({{< relref "#setup" >}}) for WildFly / JBoss EAP 7.
```

2023-03-21 09:46 UTC, tmetzke commented on content/installation/full/jboss/manual.md
> +The Camunda Spin plugin can be used to extend the engine functionality to de-/serialize object variables from and to JSON and XML. For more information, see the [Spin Reference]({{< ref "/reference/s
🔧 Let's try to use active voice here.
```suggestion
You can use the Camunda Spin plugin to extend the engine functionality to de-/serialize object variables from and to JSON and XML. For more information, see the [Spin Reference]({{< ref "/reference/spin/_index.md" >}}).
```

2023-03-21 09:46 UTC, tmetzke commented on content/update/minor/718-to-719/_index.md
> +Since Wildfly 27 drops support for Java EE in favor of Jakarta EE, you need to migrate your process applications and replace some artifacts on the application server.
❓ Should we hint people at the WildFly 26 modules that we still provide if they don't want to move to WildFly 27 but still update to 7.19.x? It currently reads a bit like "Here is 7.19.x, please move to WildFly 27". Maybe we can avoid some questions popping up in Support if we explicitly make clear that moving to WildFly 27 is optional 😃 I was thinking in a direction of "We support WildFly 27 now, it is the new default pre-packaged distro, it moves to Jakarta EE, you can also move or stay on WildFly 26, if you want to move here are the things to consider".

2023-03-21 09:46 UTC, tmetzke commented on content/update/minor/718-to-719/_index.md
> +  * `org.camunda.bpm.engine.impl.cfg.jta.JtaTransactionContextFactory` → `org.camunda.bpm.engine.impl.cfg.jta.JakartaTransactionContext`
❌ Class mixup
```suggestion
  * `org.camunda.bpm.engine.impl.cfg.jta.JtaTransactionContextFactory` → `org.camunda.bpm.engine.impl.cfg.jta.JakartaTransactionContextFactory`
```

2023-03-21 09:46 UTC, tmetzke commented on content/update/minor/718-to-719/_index.md
> +  * `org.camunda.bpm.engine.impl.cfg.jta.JtaTransactionContext` → `org.camunda.bpm.engine.impl.cfg.jta.JakartaTransactionContextFactory`
❌ Class mixup
```suggestion
  * `org.camunda.bpm.engine.impl.cfg.jta.JtaTransactionContext` → `org.camunda.bpm.engine.impl.cfg.jta.JakartaTransactionContext`
```

2023-03-21 09:46 UTC, tmetzke commented on content/update/minor/718-to-719/jboss.md
>  If not already done, download the [Camunda Platform 7.19 JBoss distribution](https://downloads.camunda.cloud/release/camunda-bpm/jboss/7.19/)
❌ This should be WildFly distribution, I think.
```suggestion
If not already done, download the [Camunda Platform 7.19 WildFly distribution](https://downloads.camunda.cloud/release/camunda-bpm/wildfly/7.19/)
```

2023-03-21 09:46 UTC, tmetzke commented on content/update/minor/718-to-719/jboss.md
> +In the following instructions, `$APP_SERVER` should be replaced with either `jboss` or `wildfly`, depending on the used application server.
❓ Does the `$APP_SERVER` variable replacement still make sense? We don't offer a JBoss subsystem anymore, do we?

2023-03-21 09:46 UTC, tmetzke commented on content/user-guide/process-applications/the-process-application-class.md
> +Remember that you additionally need a `META-INF/processes.xml` file.
🔧 We can rewrite this a bit, I think.
```suggestion
Remember to additionally add a `META-INF/processes.xml` file.
```

2023-03-21 14:06 UTC, tasso94 commented on content/installation/full/jboss/manual.md
> +## Required Setup
👍

2023-03-21 14:06 UTC, tasso94 commented on content/installation/full/jboss/manual.md
> +For Wildfly ≤26 / JBoss EAP 7, please download the [`camunda-wildfly26-modules`](https://artifacts.camunda.com/artifactory/camunda-bpm/org/camunda/bpm/wildfly/camunda-wildfly26-modules/).
👍

2023-03-21 14:10 UTC, tasso94 commented on content/installation/full/jboss/manual.md
>  `$PLATFORM_VERSION` denotes the version of the Camunda Platform you want to install or already have installed, e.g. `7.0.0`.
👍

2023-03-21 14:12 UTC, tasso94 commented on content/installation/full/jboss/manual.md
> +The Camunda Spin plugin can be used to extend the engine functionality to de-/serialize object variables from and to JSON and XML. For more information, see the [Spin Reference]({{< ref "/reference/s
👍

2023-03-21 14:12 UTC, tasso94 commented on content/update/minor/718-to-719/_index.md
> +  * `org.camunda.bpm.engine.impl.cfg.jta.JtaTransactionContextFactory` → `org.camunda.bpm.engine.impl.cfg.jta.JakartaTransactionContext`
👍

2023-03-21 14:12 UTC, tasso94 commented on content/update/minor/718-to-719/_index.md
> +  * `org.camunda.bpm.engine.impl.cfg.jta.JtaTransactionContext` → `org.camunda.bpm.engine.impl.cfg.jta.JakartaTransactionContextFactory`
👍

2023-03-21 14:16 UTC, tasso94 commented on content/user-guide/process-applications/the-process-application-class.md
> +Remember that you additionally need a `META-INF/processes.xml` file.
👍

2023-03-21 14:30 UTC, tasso94 commented on content/update/minor/718-to-719/_index.md
> +Since Wildfly 27 drops support for Java EE in favor of Jakarta EE, you need to migrate your process applications and replace some artifacts on the application server.
👍

2023-03-21 14:35 UTC, tasso94 commented
Thanks for the thorough review! Great hints 👍

2023-03-21 14:43 UTC, tmetzke approved these changes
👍 Marvelous, this looks really good 🙂 
Shall we involve a tech writer review as well?

2023-03-22 18:32 UTC, christinaausley approved these changes
Technical review in latest commit, largely adjusting Wildfly to WildFly 👍

2023-03-23 09:02 UTC, merged

2023-03-23 09:03 UTC, tasso94 commented
Great team work! Thank you, @christinaausley and @tmetzke 🙂 👍