chore(process-engine): Add Doc for HistoryCleanup Retries Config
camunda/camunda-docs-manual pull request #1471
Opened 2023-05-26 10:15 UTC by psavidis

relates to:  camunda/camunda-bpm-platform#2728

2023-05-26 11:24 UTC, yanavasileva reviewed
👍 Looks good. Let's move the property after `historyCleanupStrategy` in `History cleanup configuration parameters` section.
Hint: adding `id` to the property entry (see `historyCleanupStrategy`), creates anchor. Example: https://docs.camunda.org/manual/develop/reference/deployment-descriptors/tags/process-engine/#historyCleanupStrategy

2023-05-29 12:51 UTC, psavidis commented
Property moved under `historyCleanupStrategy`

2023-05-30 06:49 UTC, yanavasileva approved these changes
👍

2023-05-31 14:46 UTC, tasso94 requested changes

2023-05-31 14:46 UTC, tasso94 commented on content/reference/deployment-descriptors/tags/process-engine.md
> +    <td>Specifies how many times a cleanup job will be executed before an incident is raised. Default value: <code>3</code></td>
```suggestion
    <td>Specifies how often a cleanup job will be executed before an incident is raised. This property overrides the global <code>defaultNumberOfRetries</code> property which has a default value of <code>3</code></td>
```

2023-06-01 06:42 UTC, tasso94 approved these changes
👍

2023-06-01 07:05 UTC, merged