[Acquisition team] Add buttons to navbar
camunda/camunda-docs-manual pull request #1515
Opened 2023-08-08 15:53 UTC by akeller

Follow up to https://github.com/camunda/camunda-docs-theme/pull/41 and adding the changes to this part of the docs site.

When running locally, two additional shortcode files were added, but they do not appear to be part of this work and are not in this PR.

2023-08-08 18:31 UTC, pepopowitz requested changes
I think the assets should be minified, otherwise this looks great!

2023-08-08 18:31 UTC, pepopowitz commented on themes/camunda/assets/css/docs.css
The large diffs on these assets (css and js) make me think they were not minified. Did you run the `optimize` command [described in the theme docs](https://github.com/camunda/camunda-docs-theme#consuming-the-theme)?

> 2) Build and update the theme in the target location by either running:
>    1) `grunt build` for building and syncing non-minified assets
>    2) Run additionally `grunt optimize` for building and syncing minified assets

2023-08-08 18:47 UTC, akeller commented on themes/camunda/assets/css/docs.css
Fixed, thank you!

2023-08-15 15:02 UTC, tasso94 approved these changes
Looks good to me! 👍

2023-08-15 16:17 UTC, merged