chore(content): Add Documentation for enforceHistoryTimeToLive
camunda/camunda-docs-manual pull request #1523
Opened 2023-08-31 06:59 UTC by psavidis

* Add documentation for minor update from 7.19 to 7.20
* Add documentation for Configuration Properties

Related to: camunda/camunda-bpm-platform#2994

2023-09-04 14:34 UTC, tasso94 requested changes
Looks good in general but added some ideas to round up the documentation a bit.

2023-09-04 14:34 UTC, tasso94 commented on content/update/minor/719-to-720/_index.md
> +their historic data grow over time and remain uncleaned due to this configuration. In the 7.20 release,
```suggestion
their historic data grow over time and remain uncleaned due to this configuration. The history data of your executed processes will clutter the database and eventually negatively impact the engine's performance – even for runtime processes. Since the engine uses a relational database, only starting to clean up the history when a vast amount of data has been pilled up is very costly and time-consuming – in some situations, there is even no other solution than truncating tables and losing data. This is why with this release
```

2023-09-04 14:34 UTC, tasso94 commented on content/update/minor/719-to-720/_index.md
> +we decided to render the historyTimeToLive mandatory for new deployments or redeployments.
```suggestion
we decided to make the historyTimeToLive mandatory for new deployments or redeployments.
```

2023-09-04 14:34 UTC, tasso94 commented on content/update/minor/719-to-720/_index.md
> +Many of our users have installations that contain resources with null historyTimeToLive. As a result,
```suggestion
Many of our users have installations that contain model resources (BPMN, DMN, CMMN) with null historyTimeToLive. As a result,
```

2023-09-04 14:34 UTC, tasso94 commented on content/update/minor/719-to-720/_index.md
> +default value of true.
```suggestion
```

2023-09-04 14:34 UTC, tasso94 commented on content/update/minor/719-to-720/_index.md
> +the feature flag to `false`. For more information, checkout the new parameter description under <a href="{{< ref "/reference/deployment-descriptors/tags/process-engine#configuration-properties" >}}">
```suggestion
the feature flag `enforceHistoryTimeToLive` to `false`. For more information, checkout the new parameter description under <a href="{{< ref "/reference/deployment-descriptors/tags/process-engine#configuration-properties" >}}">Configuration Properties</a>.
```

2023-09-04 14:34 UTC, tasso94 commented on content/reference/deployment-descriptors/tags/process-engine.md
> +    <td>Feature flag that prevents the deployment or redeployment of any resource that contains a null historyTimeToLive (BPMN, DMN, CMMN) by throwing a ProcessEngineException. Default value: true
```suggestion
    <td>Feature flag that prevents the deployment or redeployment of any model resource (BPMN, DMN, CMMN) that contains a <code>historyTimeToLive</code> of <code>null</code> by throwing a <code>ProcessEngineException</code>. Default value: <code>true</code>.
```

2023-09-08 09:51 UTC, psavidis commented
I've applied the suggestions as-is and tested them, everything looks great 👍

2023-09-18 11:48 UTC, tasso94 approved these changes

2023-09-18 14:49 UTC, christinaausley approved these changes

2023-09-20 12:23 UTC, merged