docs(content): Add Doc for Persistence Connection Logging
camunda/camunda-docs-manual pull request #1530
Opened 2023-09-11 09:11 UTC by psavidis

* Announcement added under: content/update/minor/719-to-720

Related to: camunda/camunda-bpm-platform#3231

2023-09-19 07:49 UTC, tmetzke requested changes
👍 Well done!
🔧 I added some minor style and grammar suggestions.

2023-09-19 07:49 UTC, tmetzke commented on content/update/minor/719-to-720/_index.md
> +15. For developers: [Changes on Persistence Connection Exception Logging](#changes-on-persistence-connection-exception-logging)
🔧 We use sentence case spelling for headers and titles as described in our [writing style guide](https://confluence.camunda.com/display/HAN/Writing+Style+Cheat+Sheet#WritingStyleCheatSheet-Formatting,organizationandstructureforconceptualpiecesandimplementationsteps).
```suggestion
15. For developers: [Changes on persistence connection exception logging](#changes-on-persistence-connection-exception-logging)
```

2023-09-19 07:49 UTC, tmetzke commented on content/update/minor/719-to-720/_index.md
> +# Changes on Persistence Connection Exception Logging
🔧 We use sentence case spelling for headers and titles as described in our [writing style guide](https://confluence.camunda.com/display/HAN/Writing+Style+Cheat+Sheet#WritingStyleCheatSheet-Formatting,organizationandstructureforconceptualpiecesandimplementationsteps).
```suggestion
# Changes on persistence connection exception logging
```

2023-09-19 07:49 UTC, tmetzke commented on content/update/minor/719-to-720/_index.md
> +All persistence connection exceptions (having a cause of **SQL class 8**) will be logged with ERROR logging level from now on.
🔧 The linked article details what SQL states there are. I would argue it's enough to mention `connection exception` here since this is also what's used on that page 🙂 
```suggestion
All persistence connection exceptions will be logged with logging level ERROR instead of WARN from now on.
```

2023-09-19 10:04 UTC, psavidis commented
🔧 Applied suggestions as requested 👍

2023-09-19 10:50 UTC, tmetzke approved these changes
👍 Great!
🙃 Hint: you can batch suggestions into a single commit using `Add suggestion to batch`
![image](https://github.com/camunda/camunda-docs-manual/assets/586643/578024f3-42fe-488b-ad74-28694bae1aa5)

2023-09-21 14:50 UTC, merged

2023-09-22 07:15 UTC, tasso94 commented on content/update/minor/719-to-720/_index.md
> +You can read more about SQL connection exceptions & SQL classes [here](https://en.wikipedia.org/wiki/SQLSTATE).
Should we mention this is only relevant for API calls made via the REST API? This paragraph sounds like it affects the Java API as well.

2023-09-22 07:29 UTC, psavidis commented on content/update/minor/719-to-720/_index.md
> +You can read more about SQL connection exceptions & SQL classes [here](https://en.wikipedia.org/wiki/SQLSTATE).
That's a fair point. Here is a [change](https://github.com/camunda/camunda-docs-manual/pull/1537) which states explicitly the REST API on the title.