docs(process-engine): Add Documentation to Fetch External Task
camunda/camunda-docs-manual pull request #1562
Opened 2023-11-08 16:10 UTC by psavidis

- Rename Fetch External Task Section
- Split it into individual sections for describing sorting by priority, createTime & multi-level sorting

Related-to: #3896, #3929

2023-12-14 10:01 UTC, mboskamp requested changes
👍 I did a review of the technical content. Feel free to assign a technical writer for review as well, if you like.

2023-12-14 10:01 UTC, mboskamp commented on content/user-guide/process-engine/external-tasks.md
> +#### Multi-Level Sorting
🔧 Should we add a paragraph explaining that `priority` always takes precedence before all other sorting options?

2023-12-14 15:33 UTC, psavidis commented on content/user-guide/process-engine/external-tasks.md
> +#### Multi-Level Sorting
I've added a separate note paragraph to explain the priority precedence and its reasoning behind it.

2023-12-14 15:38 UTC, psavidis commented
Hi @christinaausley,

This commit complements the documentation with the new sorting by `createTime` and `multi-level sorting` (combining priority and createTime as sorting options) to the external tasks section.

Would you like to have a look and suggest possible changes or approve if everything looks good to you?
The section that is changed is : `Fetch External Task` | **By Priority** | **By Create Time**.

Your feedback would be much appreciated :)

2023-12-15 06:46 UTC, mboskamp commented on content/user-guide/process-engine/external-tasks.md
> +fetch and lock sorting configurations.
🔧 This sounds like the reason priority is a stronger sorting field over other fields is probability. I don't think that is accurate. The reason is that the priority feature is meant to be used to sort the external tasks by the importance of immediate execution. But I don't think this is something we need to explain here. I would simply mention that it takes precedence over any other sorting property.
🔧 This section is not about `createTime` but multi-level sorting. We should keep it more general, so it does not become inaccurate if we ever add more sorting options.

2023-12-15 07:42 UTC, psavidis commented on content/user-guide/process-engine/external-tasks.md
> +fetch and lock sorting configurations.
Just added a sentence that priority has precedence over createTime.

If we ever add another field, we can add one more sentence in the pattern "createTime has precedence over {newField}" and so on and so forth.

2023-12-15 08:14 UTC, mboskamp commented on content/user-guide/process-engine/external-tasks.md
> +fetch and lock sorting configurations.
I don't like that. In the implementation, we made efforts to make our future lives easier by choosing an extendable approach. Why shouldn't we just say, "Priority will always take precedence over any other sorting property."? It will always be true in the future. I think the multi-level sorting section does not need anything to do with the `createTime` property.

2023-12-15 08:24 UTC, psavidis commented on content/user-guide/process-engine/external-tasks.md
> +fetch and lock sorting configurations.
I've used your quoted phrase as is.

2023-12-15 17:03 UTC, christinaausley approved these changes

2023-12-18 10:51 UTC, mboskamp approved these changes

2023-12-18 10:56 UTC, merged