docs(spring-boot-integration): Update Spring Boot Matrix
camunda/camunda-docs-manual pull request #1578
Opened 2024-01-09 14:18 UTC by psavidis

Add Support of Spring Boot 3.2.1 to

Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3722

2024-01-09 15:45 UTC, tasso94 requested changes

2024-01-09 15:45 UTC, tasso94 commented on content/user-guide/spring-boot-integration/version-compatibility.md
> +    <td>3.2.x</td>
❌ Don't we support 3.1 as well as 3.2 for 7.20? Can you look up how we did this for previous versions and make it consistent? E.g., for 7.17 cf. https://docs.camunda.org/manual/7.20/user-guide/spring-boot-integration/version-compatibility/#:~:text=7.17.x%0A7.17.2,x%0A2.7.x

2024-01-10 08:14 UTC, psavidis commented on content/user-guide/spring-boot-integration/version-compatibility.md
> +    <td>3.2.x</td>
Thanks, updated accordingly.

2024-01-11 15:15 UTC, tasso94 approved these changes
Looks goods now 👍

2024-01-11 15:31 UTC, merged