style(formatting): removing platform from introduction
camunda/camunda-docs-manual pull request #1589
Opened 2024-01-24 18:18 UTC by christinaausley

Partially closes https://github.com/camunda/developer-experience/issues/117.

2024-01-26 13:08 UTC, tasso94 requested changes
Looks good to me 👍 
Just some minor hints.

2024-01-26 13:08 UTC, tasso94 commented on content/installation/camunda-bpm-run.md
> +<!--- Do we want to remove Platform from Run as well? --->
I would tend to say yes. 🙂

2024-01-26 13:08 UTC, tasso94 commented on content/installation/full/tomcat/manual.md
> +              description="Camunda Process Engine Service"
```suggestion
              description="Camunda Platform Process Engine Service"
```
This is hard-coded into our Tomcat distribution. Can we leave it as it is?

2024-01-26 13:08 UTC, tasso94 commented on content/installation/full/tomcat/manual.md
> +              description="Camunda Process Application Service"
```suggestion
              description="Camunda Platform Process Application Service"
```
This is hard-coded into our Tomcat distribution. Can we leave it as it is?

2024-01-26 21:34 UTC, akeller commented
I promise I am desperately trying not to overcomplicate this 😰 

When reviewing this PR, I am wondering about SEO and continuing to differentiate C7 from C8. Looking at:

> Install Camunda

Has me wondering if we need to add a "7" here. It's included in other areas of these docs. Certain terms and concepts should be pretty good indicators between what is C7 and C8 content, we but have so many new and prospective customers that I think we need to be really explicit in our meta data (titles and pre). 

@christinaausley @tasso94 WDYT? Is this too much or too detailed? 

Outside of this aspect, I agree with @tasso94's feedback. Let's leave any code snippets or config as-is.

2024-01-29 16:32 UTC, christinaausley commented
> I promise I am desperately trying not to overcomplicate this 😰
> 
> When reviewing this PR, I am wondering about SEO and continuing to differentiate C7 from C8. Looking at:
> 
> > Install Camunda
> 
> Has me wondering if we need to add a "7" here. It's included in other areas of these docs. Certain terms and concepts should be pretty good indicators between what is C7 and C8 content, we but have so many new and prospective customers that I think we need to be really explicit in our meta data (titles and pre).
> 
> @christinaausley @tasso94 WDYT? Is this too much or too detailed?
> 
> Outside of this aspect, I agree with @tasso94's feedback. Let's leave any code snippets or config as-is.

I'm comfortable adding the "7" for clarity -- will adjust!

2024-02-01 21:02 UTC, akeller commented on content/installation/camunda-bpm-run.md
> +title: "Install Camunda Run"
I mentioned this on the other PR, but we probably want to add a 7 to the title here so we can leave room for a C8 run.

2024-02-01 21:04 UTC, akeller commented on content/introduction/third-party-libraries/camunda-bpm-platform-license-book.md
> +title: 'Camunda License Book'
```suggestion
title: 'Camunda 7 License Book'
```

2024-02-01 21:05 UTC, akeller commented on content/installation/karaf-osgi.md
> +title: "Run Camunda using Karaf / OSGi"
```suggestion
title: "Run Camunda 7 using Karaf / OSGi"
```

2024-02-01 21:05 UTC, akeller commented on content/installation/full/wls/manual.md
> +3. (optional) [Configure location of the bpm-platform.xml file]({{< ref "/reference/deployment-descriptors/descriptors/bpm-platform-xml.md#configure-location-of-the-bpm-platform-xml-file" >}}).
Looks like this was an editor linting add that you don't want to happen
```suggestion
7. Continue to the **"Next"** page.
8. Select **"Yes, take me to the deployment's configuration screen"** and click the **"Finish"** button to complete the installation.
9. (optional) [Configure location of the bpm-platform.xml file]({{< ref "/reference/deployment-descriptors/descriptors/bpm-platform-xml.md#configure-location-of-the-bpm-platform-xml-file" >}}).
```

2024-02-01 21:06 UTC, akeller commented on content/installation/full/was/manual-liberty.md
> +1. (optional) [Configure location of the `bpm-platform.xml` file][bpm-platform-xml-config].
```suggestion
5. (optional) [Configure location of the `bpm-platform.xml` file][bpm-platform-xml-config].
```

2024-02-01 21:06 UTC, akeller commented on content/installation/full/was/manual-liberty.md
> +4. Optional components: Camunda web apps, REST API, etc.
✅ Good catch

2024-02-01 21:07 UTC, akeller commented on content/installation/camunda-bpm-run.md
> +title: "Install Camunda Run"
```suggestion
title: "Install Camunda 7 Run"
```

2024-02-01 21:08 UTC, akeller requested changes
Double check the lists to make sure they didn't get caught and incorrectly reset. I added a 7 as a suggestion in a few places. Beyond that, this looks good.

2024-02-06 15:44 UTC, tasso94 approved these changes
Looks good to me 🙂 👍

2024-02-06 19:15 UTC, akeller approved these changes

2024-02-06 23:09 UTC, merged