style(formatting): remove platform from user guide
camunda/camunda-docs-manual pull request #1595
Opened 2024-01-31 18:04 UTC by christinaausley

Partially closes https://github.com/camunda/developer-experience/issues/117.

2024-02-01 19:52 UTC, akeller commented on content/user-guide/camunda-bpm-run.md
> +title: 'Camunda Run'
This should be Camunda 7 Run so we leave room for a C8-flavored Run.

2024-02-01 19:52 UTC, akeller commented on content/user-guide/camunda-bpm-run.md
> +title: 'Camunda Run'
I don't think we need to carry this through the entire doc, but definitely the title.

2024-02-06 16:01 UTC, tasso94 requested changes
Two hints. Looks good otherwise 🙂 👍

2024-02-06 16:01 UTC, tasso94 commented on content/user-guide/spring-framework-integration/configuration.md
> +              description="Camunda 7 Process Application Service"
```suggestion
              description="Camunda Platform Process Application Service"
```

2024-02-26 16:47 UTC, merged