docs(xtac): Add useCreateTime and orderByCreateTime properties
camunda/camunda-docs-manual pull request #1632
Opened 2024-04-05 09:29 UTC by joaquinfelici

Related to https://github.com/camunda/camunda-bpm-platform/issues/4109

2024-04-05 10:40 UTC, psavidis requested changes
Thanks for adding the create time documentation to the spring boot section! I've
- added some reference to how the configuration of the two properties behaves (it's one or the other, both will throw an exception) and 
- added suggestions that explain the above

2024-04-05 10:40 UTC, psavidis commented on content/user-guide/ext-client/spring-boot-starter.md
> +        Use createTime when fetching and locking external tasks.
```suggestion
        Specifies whether tasks should be fetched based on their create time in descending order. Use this property in disjunction with order-by-create-time property or a SpringExternalTaskClientException will be thrown.
```

2024-04-05 10:40 UTC, psavidis commented on content/user-guide/ext-client/spring-boot-starter.md
> +        Use createTime when fetching and locking external tasks.
❌ According to the `ClientFactory` that [configures](https://github.com/camunda/camunda-bpm-platform/blob/5df05145727a26c7b207f3c031d03a9bbc1a5076/spring-boot-starter/starter-client/spring/src/main/java/org/camunda/bpm/client/spring/impl/client/ClientFactory.java#L109) the spring external task client, `use-create-time` property will configure the client to fetch tasks by their `createTime` in `DESC` order.

We can reflect that in the description and state also that this property has to be used in disjunction with the `order-by-create-time` property, otherwise `SpringExternalTaskClientException` will be thrown.

- `use-create-time` is a convenient flag that follows the pattern of `use-priority` for convention backwards-compatibility sake to our users which automatically orders descending
- `order-by-create-time` can be used to control explicitly the order

2024-04-05 10:40 UTC, psavidis commented on content/user-guide/ext-client/spring-boot-starter.md
> +        Specifies whether tasks should be fetched based on their createTime with a configured order. It can be either "asc" or "desc".
```suggestion
        Specifies whether tasks should be fetched based on their createTime with the given configured order. It can be either "asc" or "desc". Use this property in disjunction with order-by-create-time property or a SpringExternalTaskClientException will be thrown.
```

2024-04-05 13:45 UTC, joaquinfelici commented on content/user-guide/ext-client/spring-boot-starter.md
> +        Use createTime when fetching and locking external tasks.
@psavidis Very clear, thanks! Updated with your suggested changes.

2024-04-08 06:49 UTC, psavidis approved these changes

2024-04-08 08:04 UTC, merged