chore(content/update): Add Patch Level Tomcat 10 Support
camunda/camunda-docs-manual pull request #1660
Opened 2024-07-01 14:28 UTC by psavidis

2024-07-01 15:31 UTC, danielkelemen approved these changes

2024-07-02 09:39 UTC, psavidis commented
> ### TODO
> **Action:** Finalise (update or keep as-is) the documentation for the `7.21` backport **When:** After the finalisation of **Patch Level Update** section of master **References:** [7.22 Pull Request](https://github.com/camunda/camunda-docs-manual/pull/1647#issuecomment-2200306986)

**Status:** **Done**
**References:** [Add Tomcat Manual Installation Section](https://github.com/camunda/camunda-docs-manual/pull/1660/commits/d018c0a30ea53003c622bc2d909b1403b3739b6c), [Add Patch Level Update Section](https://github.com/camunda/camunda-docs-manual/pull/1660/commits/812fa18f0ecdd505d0bbe351c2bfe13191583e88)

2024-07-04 09:44 UTC, tasso94 requested changes

2024-07-04 09:44 UTC, tasso94 commented on content/update/patch-level.md
> +{{< /note >}}
❌ Let's add the section from the 7.21 to 7.22 migration guide here as well:
* Migrate process applications
* Migrate Java webapp plugins

2024-07-04 10:12 UTC, psavidis commented on content/update/patch-level.md
> +{{< /note >}}
Added both sections from the `7.21 to 7.22` migration guide to the Patch Level Section of the backport to make it more informative.

2024-07-04 12:42 UTC, tasso94 approved these changes

2024-07-04 12:52 UTC, psavidis commented
### Update
Review completed, moving on with merging.

2024-07-04 12:54 UTC, merged