remove(docs): remove sending telemetry feature
camunda/camunda-docs-manual pull request #1661
Opened 2024-07-12 07:31 UTC by yanavasileva

https://github.com/camunda/camunda-bpm-platform/issues/4483

2024-08-19 13:00 UTC, joaquinfelici requested changes
Looks good! Added some suggestions.

2024-08-19 13:00 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> + The [diagnostic data][] is still being collected but not send by any mean.
Seems there's a missing link here.

2024-08-19 13:00 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> + The [diagnostic data][] is still being collected but not send by any mean.
```suggestion
 The [diagnostic data][] is still being collected but not sent by any mean.
```

2024-08-19 13:00 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> +To clean up and refactor our source code, tte following process engine configuration properties have been remove.
```suggestion
To clean up and refactor our source code, tte following process engine configuration properties have been removed.
```

2024-08-19 13:00 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> +Please remove all of the occurrences of those properties, no matter of the setup that you are using
```suggestion
Please remove all of the occurrences of those properties, regardless of the setup that you are using
```

2024-08-19 13:00 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> +We recommend to remove the usage of the following API as the endpoints no longer do anything and is unnecessary.
```suggestion
We recommend to remove the usage of the following API as the endpoints no longer do anything and their usage is unnecessary.
```

2024-08-20 10:40 UTC, yanavasileva commented on content/update/minor/721-to-722/_index.md
> + The [diagnostic data][] is still being collected but not send by any mean.
Discussed. The link is declared 4 rows below.

2024-08-26 12:38 UTC, joaquinfelici approved these changes
Looks good thanks for applying suggestions 👍

2024-08-26 13:12 UTC, merged