4499 add weld cross archive bean warning
camunda/camunda-docs-manual pull request #1669
Opened 2024-08-06 08:52 UTC by psavidis

2024-08-06 11:06 UTC, tasso94 requested changes
Where can I find the installation guide hint?

2024-08-06 11:25 UTC, tasso94 requested changes

2024-08-06 11:25 UTC, tasso94 commented on content/update/minor/721-to-722/_index.md
> +The above fix is not guaranteed to work for cases that have cross-archive bean references (archive A referencing a bean from archive B).
🔧 Let's link to the broken test cases so that the Admin can understand easier if and how they are affected:

```suggestion
The above fix is not guaranteed to work for cases with bean references between WAR deployments (WAR A referencing a bean from WAR B). The following test scenarios fail on Tomcat 10:
* [CallActivityContextSwitchTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/context/CallActivityContextSwitchTest.java)
* [CdiBeanCallActivityResolutionTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanCallActivityResolutionTest.java)
```

2024-08-06 11:25 UTC, tasso94 commented on content/update/patch-level.md
> +The above fix is not guaranteed to work for cases that have cross-archive bean references (archive A referencing a bean from archive B).
🔧 Let's link to the broken test cases so that the Admin can understand easier if and how they are affected:

```suggestion
The above fix is not guaranteed to work for cases with bean references between WAR deployments (WAR A referencing a bean from WAR B). The following test scenarios fail on Tomcat 10:
* [CallActivityContextSwitchTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/context/CallActivityContextSwitchTest.java)
* [CdiBeanCallActivityResolutionTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanCallActivityResolutionTest.java)
```

2024-08-06 12:52 UTC, psavidis commented
### Update

After applying the code review suggestion the formatting of the text didn't feel right.
I've added a commit to add new line characters to make the formatting more structurally appealing.

Here are the **Before / After Screenshots** to ease up the review process:
<details><summary>Before</summary>
<img width="783" alt="Screenshot 2024-08-06 at 3 48 35 PM" src="https://github.com/user-attachments/assets/e87e5714-45a7-42f2-ba8d-c13e15c2ec58">
</details>

<details><summary>After</summary>
<img width="811" alt="Screenshot 2024-08-06 at 3 48 07 PM" src="https://github.com/user-attachments/assets/95046e55-8355-4dff-90db-da72b7abeaf6">
</details>

2024-08-06 12:57 UTC, tasso94 commented
>❓ I couldn't find a relevant section to add the hint. Where do you think the weld info could fit in the subcategories of the [Tomcat Installation guide](https://docs.camunda.org/manual/7.21/installation/full/tomcat/manual/) ?

Let's glue a note box to the installation guide where we repeat the information for Tomcat 10.

![Screenshot 2024-08-06 at 14 56 00](https://github.com/user-attachments/assets/52b6d0d1-0e3b-44c3-9c68-c3cecfc0cdd7)

Maybe something along the following lines: 

```
{{< note title="Known Limitations in Tomcat 10" class="info" >}}

**<h4>Weld Class Loading Issues</h4>**

In deployment scenarios involving one or more process applications with managed beans, classloading issues may occur if the WELD library is directly embedded in the WAR's `/WEB-INF/lib` folder.
To resolve this, move the weld library away from the war and place it into the `$CATALINA_HOME/lib` folder.

The above fix is not guaranteed to work for cases with bean references between WAR deployments (WAR A referencing a bean from WAR B). 

The following test scenarios fail on Tomcat 10:

* [CallActivityContextSwitchTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/context/CallActivityContextSwitchTest.java)
* [CdiBeanCallActivityResolutionTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanCallActivityResolutionTest.java)
{{< /note >}}
```

Should be part of the 7.21 installation guide as well.

2024-08-06 13:14 UTC, psavidis commented
> > ❓ I couldn't find a relevant section to add the hint. Where do you think the weld info could fit in the subcategories of the [Tomcat Installation guide](https://docs.camunda.org/manual/7.21/installation/full/tomcat/manual/) ?
> 
> Let's glue a note box to the installation guide where we repeat the information for Tomcat 10.
> 
> ![Screenshot 2024-08-06 at 14 56 00](https://private-user-images.githubusercontent.com/3015690/355456634-52b6d0d1-0e3b-44c3-9c68-c3cecfc0cdd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTAzMTEsIm5iZiI6MTcyMjk1MDAxMSwicGF0aCI6Ii8zMDE1NjkwLzM1NTQ1NjYzNC01MmI2ZDBkMS0wZTNiLTQ0YzMtOWM2OC1jM2NlY2ZjMGNkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTMxMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ2YTMzNWQ4YzdlMmM1NzAyZGJlM2IyZWFjOTJmYzIxOGMwNDIwNjg3N2E4MjhlNTRlNTRjMzJkZjYxODE5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nebcx5KXu9BcYrE_HlgDUrUMmzrEHBa6e2cuUBfMWoc)
> 
> Maybe something along the following lines:
> 
> ```
> {{< note title="Known Limitations in Tomcat 10" class="info" >}}
> 
> **<h4>Weld Class Loading Issues</h4>**
> 
> In deployment scenarios involving one or more process applications with managed beans, classloading issues may occur if the WELD library is directly embedded in the WAR's `/WEB-INF/lib` folder.
> To resolve this, move the weld library away from the war and place it into the `$CATALINA_HOME/lib` folder.
> 
> The above fix is not guaranteed to work for cases with bean references between WAR deployments (WAR A referencing a bean from WAR B). 
> 
> The following test scenarios fail on Tomcat 10:
> 
> * [CallActivityContextSwitchTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/context/CallActivityContextSwitchTest.java)
> * [CdiBeanCallActivityResolutionTest](https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanCallActivityResolutionTest.java)
> {{< /note >}}
> ```
> 
> Should be part of the 7.21 installation guide as well.

[Applied](https://github.com/camunda/camunda-docs-manual/pull/1669/commits/af821674ca14cad79c2d25fc9a2b88ff37395915) the suggested change. Will follow up with the `7.21` backport once this PR is finalised and merged.

2024-08-06 15:31 UTC, tasso94 requested changes

2024-08-06 15:31 UTC, tasso94 commented on content/installation/full/tomcat/manual.md
> +{{< note title="Known Limitations in Tomcat 10" class="info" >}}
🔧 I find it strange this box is located under the headline `Create the Database Schema and Tables`. Is there a better location for it?

2024-08-07 06:17 UTC, psavidis commented on content/installation/full/tomcat/manual.md
> +{{< note title="Known Limitations in Tomcat 10" class="info" >}}
Moved the note to the suggested location.

PS: Now having two notes looks lengthy at the beginning of the page but its still more relevant.

2024-08-07 06:44 UTC, tasso94 requested changes

2024-08-07 06:44 UTC, tasso94 commented on content/installation/full/tomcat/manual.md
> +  {{< /note >}}
```suggestion
```

2024-08-08 07:13 UTC, tasso94 approved these changes
Looks good now 🙂 👍 I replaced the word `fix` with `workaround`.

2024-08-08 07:26 UTC, merged