4163 update quarkus 314 properties docs
camunda/camunda-docs-manual pull request #1675
Opened 2024-09-04 13:48 UTC by psavidis

2024-09-04 14:42 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +1. For developers: [Quarkus 3.14 Extension Update](#quarkus-3-14-extension-update)
Notification of the users for the changes in Quarkus 3.14, the affected properties and references

2024-09-04 14:42 UTC, psavidis commented on content/user-guide/quarkus-integration/configuration.md
> +quarkus.camunda.generic-config.cmmn-enabled=false
Update of all referenced properties in the Quarkus Configuration page

2024-09-05 11:50 UTC, mboskamp requested changes
🔧 This is very good already. I was wondering if we could provide a little more background information to our users about why we decided to introduce a breaking change.

2024-09-05 11:50 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +The Quarkus Extension has been updated to use Quarkus `3.14`. This version brings its own features and changes.
🔧 Let's make it clear, that we are talking about our extension which was upgraded.

```suggestion
The Camunda Quarkus Extension has been updated to use Quarkus `3.14`. This version brings its own features and changes.
```

2024-09-05 11:50 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +## Property Examples
🙃 I think it makes sense to treat this section as child of `Breaking Changes` because it's an example of a required change.
```suggestion
### Property Examples
```

2024-09-05 11:50 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +## Configuration Page Update
🙃 I think it makes sense to treat this section as child of `Breaking Changes` because it's an example of a required change.
```suggestion
### Configuration Page Update
```

2024-09-05 11:50 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.enforce-history-time-to-live` **becomes** `quarkus.camunda.generic-config.enforce-history-time-to-live`
🔧 Can you add one or two sentences explaining the reason for the change? The Quarkus migration guide encourages using named ConfigMappings, and we chose to adopt it to future-proof the extension. This requires using a different namespace for generic Camunda configuration properties for [engine](https://docs.camunda.org/manual/7.20/reference/deployment-descriptors/tags/process-engine/#configuration-properties) and [job executor](https://docs.camunda.org/manual/7.20/reference/deployment-descriptors/tags/job-executor/) configuration. We already use this approach for the [Camunda Spring Boot Starter](https://docs.camunda.org/manual/7.20/user-guide/spring-boot-integration/configuration/#generic-properties).

2024-09-05 11:50 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +For a complete list, see the [Quarkus 3.14 Release](https://quarkus.io/blog/quarkus-3-14-1-released) blog post.
```suggestion
For a complete list, see the [Quarkus 3.14.2 Release](https://quarkus.io/blog/quarkus-3-14-2-released) blog post.
```

2024-09-06 09:10 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +For a complete list, see the [Quarkus 3.14 Release](https://quarkus.io/blog/quarkus-3-14-1-released) blog post.
Thanks for the catch.
I've setup a task when the [Bump to 3.15 versio](https://github.com/camunda/camunda-bpm-platform/issues/4580)n is performed to update the patch version in the docs as well.

2024-09-06 09:20 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +## Property Examples
The same can be argued about the Configuration Page Update section.
I would prefer to avoid nesting if possible. 

The intention of the headers is to communicate to the user effectively that

i) There is a breaking change
ii) a couple of indicative examples to visualise the change, making it more evident
iii) clarify the configuration page is updated and
iv) point to sources

2024-09-06 10:05 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +## Configuration Page Update
Same as [point for Property Examples](https://github.com/camunda/camunda-docs-manual/pull/1675/files#r1745275025)

2024-09-06 10:44 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.enforce-history-time-to-live` **becomes** `quarkus.camunda.generic-config.enforce-history-time-to-live`
Added basically an explanation under the `Property Examples` section inspired by your suggestion.

2024-09-09 09:26 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.enforce-history-time-to-live` **becomes** `quarkus.camunda.generic-config.enforce-history-time-to-live`
You added

> Reason for Change: The Quarkus migration guide encourages using named ConfigMappings, and we chose to adopt it to future-proof the extension. This requires using the new namespace generic-config.

🔧 I would expect that information in the Breaking Changes section. Users will want to read one section to understand our intentions.

2024-09-09 09:26 UTC, mboskamp commented on content/update/minor/721-to-722/_index.md
> +## Property Examples
🙃 I would argue that all the information in this content fits in one section. You could still structure it with bold text (like you did with "Reason for Change"). We [don't usually](https://docs.camunda.org/manual/7.21/update/minor/720-to-721/#feel-engine-1-17-upgrade) add a new headline to point to other sources. In my opinion, the amount of information here does not justify five headlines. Simple is good. Feel free to ignore.

2024-09-09 14:07 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +## Property Examples
Done according to the suggestio

2024-09-09 14:07 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +## Configuration Page Update
Followed the suggestion

2024-09-09 14:07 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.enforce-history-time-to-live` **becomes** `quarkus.camunda.generic-config.enforce-history-time-to-live`
Moved the reason for change under breaking changes section.

2024-09-09 14:08 UTC, mboskamp approved these changes

2024-09-09 14:14 UTC, psavidis commented
Hello @christinaausley,

I'd like to kindly request your input for changes in the content, style or any other contribution you can think of for this pull request.

**Context**: `Quarkus 3.14 Update Documentation`
**Where**: Minor Release Guide

If there is anything you'd like to change, feel free to add your suggestions.

Thank you in advance,
Petros

2024-09-12 12:43 UTC, conceptualshark approved these changes
Some minor non-blocking suggestions - otherwise this looks good to me from a docs perspective!

2024-09-12 12:43 UTC, conceptualshark commented on content/update/minor/721-to-722/_index.md
> +As a result, we decided to accept a config migration at this point to be consistent with the new behaviour of the framework (see [property examples](#property-examples) below)
```suggestion
A config migration is required to remain consistent with the new behavior of the framework (see [property examples](#property-examples) below).
```

Not sure if the C7 docs have the same American English spelling standards, so feel free to ignore if not! 👍

2024-09-12 12:43 UTC, conceptualshark commented on content/update/minor/721-to-722/_index.md
> +
```suggestion
The config properties now follow a similar scheme to the [Camunda Spring Boot Starter Configuration]({{< ref "/user-guide/spring-boot-integration/configuration.md#generic-properties" >}}).

```

2024-09-12 12:43 UTC, conceptualshark commented on content/update/minor/721-to-722/_index.md
> +If you want to read more on how Quarkus Extensions treat configuration differently, checkout the  [Quarkus 3.14 Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#for-ext
```suggestion
For a detailed guide on the new Quarkus properties, visit the updated [Quarkus Configuration]({{< ref "/user-guide/quarkus-integration/configuration.md" >}}) page.

To read more on how Quarkus extensions treat configuration differently, see the [Quarkus 3.14 Migration Guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#for-extension-developers).
```

2024-09-12 12:59 UTC, merged

2024-09-16 14:56 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.job-executor.thread-pool.max-pool-size` **becomes** `quarkus.camunda.job-executor.generic-config.thread-pool.max-pool-size`
Hello @psavidis ,

I was checking these changes, and I may be missing something, but isn't this incorrect?
Only non specific properties that are mapped to the `genericConfig` map should be impacted. This *shouldn't* include properties:
- `job-executor.thread-pool.max-pool-size`
- `job-executor.thread-pool.queue-size`

We can see [here](https://github.com/camunda/camunda-bpm-platform/blob/master/quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/job-executor-application.properties) that these two properties haven't changed.

2024-09-17 06:31 UTC, psavidis commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.job-executor.thread-pool.max-pool-size` **becomes** `quarkus.camunda.job-executor.generic-config.thread-pool.max-pool-size`
The above is correct 👍 
Indeed the job executor properties are a poor selection for demonstrating the change in the docs

**Proof**: Changing the values in the test file [mixed-application.properties](https://github.com/camunda/camunda-bpm-platform/blob/master/quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/mixed-application.properties) makes [CamundaEngineConfigFileTest#L70](https://github.com/camunda/camunda-bpm-platform/blob/master/quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigFileTest.java#L70) fail.

2024-09-17 06:37 UTC, joaquinfelici commented on content/update/minor/721-to-722/_index.md
> +- `quarkus.camunda.job-executor.thread-pool.max-pool-size` **becomes** `quarkus.camunda.job-executor.generic-config.thread-pool.max-pool-size`
Thanks for checking. In that case changes in file [configuration.md](https://github.com/camunda/camunda-docs-manual/blob/c3f6b937ad202a829828bbca1201b7c1f9179bb1/content/user-guide/quarkus-integration/configuration.md?plain=1#L226) are also incorrect. I can correct these in a new PR to prepare for the 3.15 upgrade.