feat(oauth2): add Spring Security OAuth2 documentation
camunda/camunda-docs-manual pull request #1677
Opened 2024-09-10 08:48 UTC by danielkelemen

https://github.com/camunda/camunda-bpm-platform/issues/4454

2024-09-10 08:50 UTC, danielkelemen commented
@yanavasileva, PR is not complete yet but I'm adding you already to gather early feedback because it's a complex topic.

2024-09-12 07:19 UTC, yanavasileva reviewed
First-time read comments.

2024-09-12 07:19 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +camunda.bpm.oauth2:
❓ We need to add the properties to the [configurations table](https://github.com/camunda/camunda-docs-manual/blob/4454-oauth2-docs/content/user-guide/spring-boot-integration/configuration.md#camunda-engine-properties) or we don't want to advertise the feature there?

2024-09-12 07:19 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +Additionally, also follow the security recommendations specified by your identity provider.
✍️ I think similar thing (with link to this page?) must be mentioned here as well: https://docs.camunda.org/manual/latest/user-guide/security/#security-configuration-in-the-external-environment
(Or somewhere else on that page)

2024-09-12 07:19 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +## Disabling Auto Configuration
📓 This needs to be manually tested.

2024-09-12 07:19 UTC, yanavasileva commented on content/user-guide/camunda-bpm-run.md
❓ Do we need to add anything else on this page.

2024-09-26 11:16 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +camunda.bpm.oauth2:
I added configuration sections where needed (identity provide & logout)

2024-09-26 11:19 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +Starts if there is **no** OAuth2 client registration configured. This class configures the Spring
Changed to _Configuration activates_

2024-09-26 11:20 UTC, danielkelemen commented on content/user-guide/camunda-bpm-run.md
I added a few more things about configs, logout, customizing.

2024-09-26 11:37 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +In order to create an initial user in your application, you can either use the `camunda.bpm.admin-user` property:
I added a bit more info, let me know what you think.

2024-09-26 11:40 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +## Disabling Auto Configuration
Test both in Spring Boot, they work.

2024-09-27 07:47 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +Additionally, we also mark and explain a few lines:
💬 I also added a full example config with some hints. Let me know if you find it unnecessary.

2024-09-27 08:04 UTC, danielkelemen commented
Hi @christinaausley, would have time today to review this? Thank you!

2024-09-27 12:42 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +to grant administrator authorizations for a particular OAuth2 user or group.
🔧 The two options are too far away for me. Could you consider bullets or rewording?

2024-09-27 12:42 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +camunda.bpm.oauth2:
❓ Does this mean that they won't be mentioned in the default configuration page of Spring boot? I don't see changes there.

2024-09-27 12:42 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +## Disabling Auto Configuration
I forgot that I wrote that and I was about to ask again. 😄

2024-09-27 12:49 UTC, yanavasileva commented on content/user-guide/camunda-bpm-run.md
I don't see anything added on the page? Are any commits missing or?

2024-09-27 12:55 UTC, danielkelemen commented on content/user-guide/camunda-bpm-run.md
Sorry, I mixed the source up, I didn't add anything more here.
I don't think we need more, `--oauth2` flag is specified and linked.

2024-09-27 12:56 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +camunda.bpm.oauth2:
Ah good point, I overlooked it, I will add them there too.

2024-09-27 13:23 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +to grant administrator authorizations for a particular OAuth2 user or group.
Added bullet points.

2024-09-27 15:48 UTC, yanavasileva requested changes
I am done with the second round of feedback.

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +This is achieved with a custom [identity service]({{< ref "/user-guide/process-engine/identity-service.md" >}}), called {{< javadocref page="org/camunda/bpm/spring/boot/starter/security/oauth2/impl/O
🔧 Missing fullstop:
```suggestion
This is achieved with a custom [identity service]({{< ref "/user-guide/process-engine/identity-service.md" >}}), called {{< javadocref page="org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProvider.html" text="OAuth2IdentityProvider" >}}.
```

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +Additionally, also follow the security recommendations specified by your identity provider.
We can iterate on the docs after we receive user's feedback. As long as all configuration must be done on identity provider's side, we don't need to list explicitly anything.. You already added the token lifetime for which we can anticipate to be asked for. So we are good.

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +./start.sh --webapps --rest --example --oauth2
🔧 The example is not recommended for production so I suggest to remove it:
```suggestion
./start.sh --webapps --rest --oauth2
```

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +1. The `camunda.bpm.admin-user` property to create an admin user with authorizations:
🙃 
```suggestion
1. The `camunda.bpm.admin-user` property to create an administrator user with authorizations:
```

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +See [Configuration](#configuration) section for more infos.
🙃 
```suggestion
See [Configuration](#configuration) section for more information.
```

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +See [Configuration](#configuration-1) section for more infos.
❌ That linking is not working locally for me. I suggest to remove the reference to avoid confusion.
```suggestion
Check the next section for more information.
```

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +See [Configuration](#configuration) section for more infos.
🙃 
```suggestion
See [Configuration](#configuration) section for more details.
```

2024-09-27 15:48 UTC, yanavasileva commented on content/user-guide/spring-boot-integration/spring-security.md
> +We use debug logging for several things such as bean registrations, user authentication or logout and token authorization.
🔧 
```suggestion
You can switch the level of the following logger to track: bean registrations, user authentication or logout, and token authorization.
```

2024-09-30 13:53 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +See [Configuration](#configuration-1) section for more infos.
Weird, it's working for me.

2024-09-30 13:55 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +See [Configuration](#configuration) section for more infos.
Changed to _information_.

2024-09-30 13:58 UTC, danielkelemen commented on content/user-guide/spring-boot-integration/spring-security.md
> +We use debug logging for several things such as bean registrations, user authentication or logout and token authorization.
Applied suggestion.

2024-09-30 16:43 UTC, yanavasileva approved these changes
👍 Good. Thank you for considering my feedback.

2024-10-04 08:37 UTC, merged