docs(content/mig-guide): migration to HeroDevs XLTS libraries
camunda/camunda-docs-manual pull request #1709
Opened 2024-11-20 15:58 UTC by venetrius

related to: https://github.com/camunda/camunda-bpm-platform/issues/4549

2024-11-25 12:46 UTC, venetrius commented on content/update/patch-level.md
> +## 7.22.0 to 7.22.1 / 7.21.5 to 7.21.6 /  7.20.8 to 7.20.9
We already had a section for 
```
## 7.22.0 to 7.22.1
```
I created a new section as this is relevant also for migrating: `7.21.5 to 7.21.6 /  7.20.8 to 7.20.9`
Let me know if there is a better way to do this.

2024-11-25 15:58 UTC, venetrius commented
This change is blocked, moved into draft.

2024-11-26 10:13 UTC, venetrius commented on content/introduction/third-party-libraries/_index.md
>  ## XLTS for AngularJS
This section is referenced by old migration guides so I opted to only edit it, but not remove.

2024-11-26 11:08 UTC, tasso94 requested changes

2024-11-26 11:08 UTC, tasso94 commented on content/update/patch-level.md
> +Starting with 7.22.1,  7.21.6, 7.20.9 the following libraries are replaced with XLTS versions provided by XLTS.dev by HeroDevs, Incl:
```suggestion
These patches replace Bootstrap NES and AngularJS NES versions provided by HeroDevs, Inc.:
```

2024-11-26 11:08 UTC, tasso94 commented on content/update/patch-level.md
> +*  *angular-ui-bootstrap*
```suggestion
* *AngularJS* (technical names: `angular`, `angular-animate`, `angular-cookies`, `angular-loader`, `angular-mocks`, `angular-resource`, `angular-route`, `angular-sanitize`, `angular-touch`)
*  *angular-ui-bootstrap*
```

2024-11-26 11:08 UTC, tasso94 commented on content/update/patch-level.md
> +*  *Bootstrap*
```suggestion
*  *Bootstrap*

Where AngularJS, angular-ui-bootstrap, angular-translate, angular-moment, and Bootstrap were licensed entirely under the MIT license, Bootstrap NES and AngularJS NES by HeroDevs, Inc. licenses additional parts under the HeroDevs NES License. By downloading and using Camunda with Bootstrap NES and AngularJS NES by HeroDevs, Inc., you agree to the terms of the HeroDevs NES License. You can find the HeroDevs NES License terms in our [License Book](TODO: ADD LINK TO LICENSE BOOK).
```

2024-11-26 11:08 UTC, tasso94 commented on content/update/patch-level.md
> +Please see our [third-Party libraries documentation]({{< ref "/introduction/third-party-libraries/_index.md#web-applications-cockpit-tasklist-admin" >}}) for details.
```suggestion
Please see our [third-Party libraries documentation]({{< ref "/introduction/third-party-libraries/_index.md#web-applications-cockpit-tasklist-admin" >}}) for details.
```

2024-11-26 12:18 UTC, venetrius commented on content/introduction/third-party-libraries/_index.md
> +Starting with versions 7.20.9, 7.21.6, 7.22.1 the Camunda web applications use a set of third-party libraries through XLTS.dev by HeroDevs, Incl
Applied suggestions and they updated all cases.

2024-11-26 12:44 UTC, tasso94 requested changes
Looks almost ready to me. One more thing:
❓ Should we add what we have in the patch level guide with a few adjustments to the minor update guide under `/update/minor/722-to-723/`?

2024-11-26 12:44 UTC, tasso94 commented on content/introduction/third-party-libraries/_index.md
> +### Bootstrap NES and AngularJS NES by HeroDevs, Inc.
```suggestion
## Bootstrap NES and AngularJS NES by HeroDevs, Inc.
```

2024-11-26 12:44 UTC, tasso94 commented on content/update/patch-level.md
> +These patches replace Bootstrap NES and AngularJS NES versions provided by HeroDevs, Inc.:
```suggestion
These patches replace the following libraries with versions of Bootstrap NES and AngularJS NES by HeroDevs, Inc.:
```

2024-11-26 14:33 UTC, venetrius commented on content/introduction/third-party-libraries/_index.md
> +### Bootstrap NES and AngularJS NES by HeroDevs, Inc.
Added to local commit.

2024-11-26 14:37 UTC, venetrius commented
> Looks almost ready to me. One more thing: ❓ Should we add what we have in the patch level guide with a few adjustments to the minor update guide under `/update/minor/722-to-723/`?

Good point, added update to minor update guide under `/update/minor/722-to-723/`

2024-11-26 15:07 UTC, tasso94 approved these changes
Looks almost perfect now! Just a tiny typo in the new migration guide addition. You can merge without further review once fixed.

2024-11-26 15:07 UTC, tasso94 commented on content/update/minor/722-to-723/_index.md
> +Camunda 7.23.1 replaces the following libraries with versions of Bootstrap NES and AngularJS NES by HeroDevs, Inc.:
```suggestion
Camunda 7.23.0 replaces the following libraries with versions of Bootstrap NES and AngularJS NES by HeroDevs, Inc.:
```

2024-11-26 15:24 UTC, merged