chore(rpa): add first documentation for RPA bridge
camunda/camunda-docs-manual pull request #643
Opened 2020-07-20 12:49 UTC by mboskamp

Related to CAM-12169

2020-08-03 11:03 UTC, koevskinikola commented on content/installation/camunda-bpm-rpa-bridge.md
> +  Please note that the RPA bridge is only available as enterprise edition.
I think this should state that the bridge is available "in" or "through" the EE version. Or for EE customers.
```suggestion
  Please note that the RPA bridge is only available in the Enterprise Edition.
```

2020-08-03 11:04 UTC, koevskinikola commented on content/installation/camunda-bpm-rpa-bridge.md
> +If you need to install Java Runtime Environment, you can [find the download from Oracle here](https://www.oracle.com/java/technologies/javase-downloads.html).
```suggestion
If you need to install a Java Runtime Environment, you can [find the download from Oracle here](https://www.oracle.com/java/technologies/javase-downloads.html).
```

2020-08-03 11:05 UTC, koevskinikola commented on content/installation/camunda-bpm-rpa-bridge.md
> +1. Downlaod the Camunda RPA Bridge distro from [here](). TODO
Typo. Also the download link needs to be added.
```suggestion
1. Download the Camunda RPA Bridge distro from [here](). TODO
```

2020-08-03 11:06 UTC, koevskinikola commented on content/installation/camunda-bpm-rpa-bridge.md
> +1. create and deploy a model that includes an RPA service task (see the [user guide]({{< ref "/user-guide/camunda-bpm-rpa-bridge.md" >}} for more information)
Fix typo. We can also further specify the section of the docs.
```suggestion
1. Create and deploy a model that includes an RPA service task (see the [user guide]({{< ref "/user-guide/camunda-bpm-rpa-bridge.md#set-up-an-rpa-task" >}} for more information)
```

2020-08-03 11:08 UTC, koevskinikola commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +For detailed instructions on how to connect your first RPA bot to a BPMN model (using Cawemo and the Camunda Modeler) and execute it from a running process instnace using the Camunda engine head over
Typo
```suggestion
For detailed instructions on how to connect your first RPA bot to a BPMN model (using Cawemo and the Camunda Modeler) and execute it from a running process instance using the Camunda engine, head over to our [installation guide]({{< ref "/installation/camunda-bpm-rpa-bridge.md" >}})
```

2020-08-03 11:09 UTC, koevskinikola commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +The Camunda RPA bridge serves a connector between Camunda (BPMN) on the one side and UIPath (RPA) on the other side. Processes running inside the Camunda engine can define external tasks that are mar
Fix typo. Also, should we provide a link to the `UIPath` website?
```suggestion
The Camunda RPA bridge serves as a connector between Camunda (BPMN) on the one side and UIPath (RPA) on the other side. Processes running inside the Camunda engine can define external tasks that are marked as RPA tasks.
```

2020-08-03 11:12 UTC, koevskinikola commented on content/installation/camunda-bpm-rpa-bridge.md
> +1. Configure the bridge with the shipped `application.yml` file (see the [user guide]({{< ref "/user-guide/camunda-bpm-rpa-bridge.md" >}}) for a full list of configuration options).
We can further specify the section of the User Guide docs:
```suggestion
1. Configure the bridge with the shipped `application.yml` file (see the [user guide]({{< ref "/user-guide/camunda-bpm-rpa-bridge.md#camunda-bpm-rpa-bridge-configuration" >}}) for a full list of configuration options).
```

2020-08-03 11:15 UTC, koevskinikola commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +By default the bridge listens for tasks with the topics `uipath` and `RPA`. If a process instance reaches an external task with one of these topics, the bridge will be able to fetch and lock them. On
```suggestion
By default, the bridge listens for tasks with the topics `uipath` and `RPA`. If a process instance reaches an external task with one of these topics, the bridge will be able to fetch and lock them. Once a task is locked, the bridge will try to forward it to your installation of UIPath which will take care of executing the associated robots.
```

2020-08-03 11:19 UTC, koevskinikola commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +* An on-premise installation of [UIPath Orchestrator](https://www.uipath.com/product/orchestrator).
Making the bullet points consistent:
```suggestion
* An on-premise installation of [UIPath Orchestrator](https://www.uipath.com/product/orchestrator)
```

2020-08-17 15:22 UTC, mboskamp commented on content/installation/camunda-bpm-rpa-bridge.md
> +  Please note that the RPA bridge is only available as enterprise edition.
I don't think this change is necessary as the bridge will not be bundled within something else (_in_ the Enterprise Edition). It is an Enterprise Edition itself and there is no Community Edition.

What do you think about this?
```suggestion
  Please note that the RPA bridge is only available for customers with access to our enterprise artifacts.
```

2020-08-20 09:48 UTC, volkergersabeck commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +To tell the bridge for which RPA process a bot should be started, it is necessary to add a [custom extension]({{< ref "/user-guide/model-api/bpmn-model-api/extension-elements.md" >}}) with the name `
"value equal to the package name of the released process in UIPath"

2020-08-20 09:49 UTC, volkergersabeck commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +      <camunda:property name="bot" value="UIPathProcessName" />
value="UIPathPackageName" />

2020-08-31 06:53 UTC, koevskinikola commented on content/installation/camunda-bpm-rpa-bridge.md
> +  Please note that the RPA bridge is only available as enterprise edition.
Looks good! :+1:

2020-08-31 06:57 UTC, koevskinikola approved these changes
From my side, as soon as the remaining suggestions are resolved, the PR can be merged.

2020-08-31 08:02 UTC, mboskamp commented
Thanks @koevskinikola, thanks @volkergersabeck. I will leave the PR open, because we will only release it when the bridge will be released. Until then feel free to add your suggestions to this PR.

2020-09-09 14:12 UTC, tmetzke commented on content/installation/camunda-bpm-rpa-bridge.md
> +1. Create and deploy a model that includes an RPA service task (see the [user guide]({{< ref "/user-guide/camunda-bpm-rpa-bridge.md#set-up-an-rpa-task" >}} for more information)
```suggestion
1. Create and deploy a model that includes an RPA service task (see the [user guide]({{< ref "/user-guide/camunda-bpm-rpa-bridge.md#set-up-an-rpa-task" >}}) for more information)
```

2020-09-22 13:02 UTC, tmetzke requested changes
Looks good overall 👍 
Just a minor thing for the telemetry config option

2020-09-22 13:02 UTC, tmetzke commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +</table>
This should probably simply go into `Configure Basic Properties`. In order to reference this somewhere, you will need to add an `id` here in the `<tr>` as well, don't you?

2020-09-23 09:34 UTC, mboskamp commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +</table>
Will move the section up. Not sure about the id. You can reference the section with the header name (#enable-telemetry).

2020-09-23 09:46 UTC, tmetzke commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +</table>
Ah ok, no I meant to simply integrate the config option into the other section, next to the license key.
And then add an id to the `tr` and reference this from the `Telemetry` section

2020-09-23 11:23 UTC, mboskamp commented on content/user-guide/camunda-bpm-rpa-bridge.md
> +</table>
Got it. Makes sense.

2020-09-24 11:38 UTC, tmetzke approved these changes

2020-09-25 12:53 UTC, merged