docs(introduction): add telemetry page
camunda/camunda-docs-manual pull request #677
Opened 2020-09-02 12:06 UTC by yanavasileva

* improve process engine configuration page
* add links to rest docs to general information

Related to CAM-12125

2020-09-04 12:36 UTC, tasso94 requested changes
LGTM! Please find some reworded paragraphs and hints below:

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +The full list of the collected data can be found below, followed by a real case example. The data can be separated into three groups: general data, meta/environment data, and usage data.
```suggestion
You can find below the full list of the collected data, followed by a real-world example. The data can be categorized into three groups: general data, meta/environment data, and usage data.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +### General data
```suggestion
### General Data

```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +Contains information about the process engine.
```suggestion
The "General Data" category contains information about the process engine:
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +* product edition - identifying whether `community` or `enterprise` version is used
```suggestion
* Installation - an id that is stored as process engine configuration property
* Product name - the name of the product (i.e., `Camunda BPM Runtime`)
* Product version - the version of the process engine (i.e., `7.X.Y`)
* Product edition - the edition of the product (i.e., either `community` or `enterprise`)
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +Contains information about the environmental setup.
```suggestion
The "Meta/Environment Data" category contains information about the environmental setup:
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +* application server vendor and version
```suggestion
* Database vendor and version
* Application server vendor and version
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +### Usage data
```suggestion
### Usage Data
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +Contains entries that give insights into which features and components are used in the process engine.
```suggestion
The "Usage Data" category contains information about the used features and components of the process engine:
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +* commands count - the count of executed commands after the last retrieved data
```suggestion
* Commands count - the count of commands executed within 24 hours
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +A telemetry logger exists that logs details for the information that is sent or problems when the data is sent when the telemetry is enabled. For further informaion check the [Logging]({{< ref "/user
```suggestion
A telemetry logger exists to log details about the sent information and error details in case the data couldn't be collected or sent. For further information check the [Logging]({{< ref "/user-guide/logging.md" >}}) page in the User Guide.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +The application server information cannot be obtained in an embedded process engine setup where no web applications (e.g. Tasklist, Cockpit, Rest application) are not deployed and used.
```suggestion
The application server information cannot be obtained in an embedded process engine setup where no web applications (e.g. Tasklist, Cockpit, REST application) are not deployed and used.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +Use the `initializeTelemetry` configuration [property][engine-config] to enable the telemetry before starting the process engine. Just add it to you process engine configuration:
```suggestion
Use the `initializeTelemetry` configuration [flag][engine-config] to enable the telemetry before starting the process engine. You can simply add it to your process engine configuration:
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +Later on the telemetry can be enabled/disabled via the engine API.
```suggestion
Later on, the telemetry can be enabled/disabled via the engine API.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +The configuration of the telemetry can be changed via our API.
```suggestion
You can change the telemetry configuration via our API.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +To achieve the same, you can also use the respective Rest API request. For more information, have a look at the [telemetry][telemetry-config-rest] page in the Rest API documentation.
```suggestion
To achieve the same, you can also use the respective REST API request. For more information, have a look at the [telemetry][telemetry-config-rest] page in the REST API documentation.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +Before you install a Camunda BPM Runtime version >= 7.14.0-alpha1 or activate the telemetry functionality, please make sure that you are authorized to take this step, and that the installation or act
```suggestion
Before you install a Camunda BPM Runtime version >= 7.14.0-alpha1 or activate the telemetry functionality, please make sure that you are authorized to take this step, and that the installation or activation of the [telemetry functionality][engine-config] is not in conflict with any company-internal policies, compliance guidelines, any contractual or other provisions or obligations of your company.
```

2020-09-04 12:36 UTC, tasso94 commented on content/introduction/telemetry.md
> +In case you want further details, you can have a look at the implementation of the telemetry topic in [our code](https://github.com/camunda/camunda-bpm-platform/blob/2015f4902853bf688216c9f75e846256d
```suggestion
In case you want further details, you can have a look at the implementation of the telemetry topic in [our code](https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java#L69-L98).
```
Can we link here to `master`? The implementation might change in the future, and this documentation "pretends" that the implementation won't ever change. If we change the location of the `TelemetrySendingTask`, we would be notified for the master branch due to docs link checking, right? I think this is enough to maintain that the link keeps working in the future.

Maybe we can add some more text that this shows the current development version and older implementation versions can be found by changing `master` to the respective `7.X.0` version.

2020-09-04 12:36 UTC, tasso94 commented on content/reference/deployment-descriptors/tags/process-engine.md
> +          For more information and complete list of the information that is collected, please check the <a href="{{< ref "/introduction/telemetry.md" >}}">Telemetry</a> page.
```suggestion
          For more information and a complete list of the data that is collected, please check the <a href="{{< ref "/introduction/telemetry.md" >}}">Telemetry</a> page.
```

2020-09-04 12:36 UTC, tasso94 commented on content/reference/rest/telemetry/get-telemetry.md
> +Fetches the telemetry configuration. For more information on telemetry topic, visit the [Telemetry]({{< ref "/introduction/telemetry.md" >}}) page.
```suggestion
Fetches the telemetry configuration. For more information on the telemetry topic, visit the [Telemetry]({{< ref "/introduction/telemetry.md" >}}) page.
```

2020-09-04 12:36 UTC, tasso94 commented on content/user-guide/logging.md
> +    <td>logs details for data that is sent and the problems with telemetry configuration</td>
```suggestion
    <td>logs details about the sent information and error details in case the data couldn't be collected or sent</td>
```

2020-09-04 12:36 UTC, tasso94 commented on content/user-guide/logging.md
> +In order to inspect what data is sent when [Telemetry]({{< ref "/introduction/telemetry.md" >}}) is enabled, please enable the Telemetry logger. The logger will help for troubleshooting if no data is
```suggestion
In order to inspect what data is sent when [Telemetry]({{< ref "/introduction/telemetry.md" >}}) is enabled, please enable the Telemetry logger. The logger will help with troubleshooting if no data is sent.
```

2020-09-04 12:36 UTC, tasso94 commented on content/user-guide/logging.md
> +Find below an example of the log entries when the data is sent.
```suggestion
Please find below an example of the log entries when the data is sent:
```

2020-09-04 13:29 UTC, yanavasileva commented on content/introduction/telemetry.md
> +In case you want further details, you can have a look at the implementation of the telemetry topic in [our code](https://github.com/camunda/camunda-bpm-platform/blob/2015f4902853bf688216c9f75e846256d
I will consider adding `master` and a note to it.
As far as I know the version place holder is not easily achievable, Nikola worked on something in that direction, I will double-check.

2020-09-04 14:54 UTC, tasso94 approved these changes
Awesome! ✨

2020-09-04 14:54 UTC, tasso94 commented on content/introduction/telemetry.md
> +* Commands count - the count of executed commands after the last retrieved data. It could be from the last 24 hours if the data have been reported then and the process engine has not been close durin
```suggestion
* Commands count - the count of executed commands after the last retrieved data. It could be from the previous 24 hours if the data have been reported then, and the process engine has not been closed during that time. Whenever the process engine is shutdown, the currently collected data is reported immediately.
```

2020-09-07 04:08 UTC, impactpractise commented on content/introduction/telemetry.md
> +With the Camunda BPM Runtime, we strive to offer excellent user experience at a high and stable level. Collecting environment and usage data helps us to keep the level up. The insights into typical e
At Camunda, we strive to offer excellent user experiences at a high and stable level.

2020-09-07 04:18 UTC, impactpractise requested changes

2020-09-07 04:18 UTC, impactpractise commented on content/introduction/telemetry.md
> +With the Camunda BPM Runtime, we strive to offer excellent user experience at a high and stable level. Collecting environment and usage data helps us to keep the level up. The insights into typical e
At Camunda, we strive to offer excellent user experience at a high and stable level. On a strict opt-in basis, we are looking to collect environment and usage data to further improve the user experience for you. These insights help us to understand typical environment setups and product usage patterns and will be used data informed product improvement decisions to your benefit.

The Telemetry Reporter is disabled by default and only collects and sends data after you explicitly enable a [process engine configuration][engine-config] flag. The configuration can be changed at any time during runtime via Java API or [REST API][telemetry-config-rest].

The collected data will be sent once in 24 hours via HTTP, which is scheduled by a Java timer task. We took good care that your process automation will not be negatively affected in case the Telemetry Reporter suddenly faces an unexpected error. Furthermore, no data will be collected and sent when you stop the process engine.

2020-09-07 04:18 UTC, impactpractise commented on content/introduction/telemetry.md
> +## Collected Data
## Collected Data

Below you find the full list of data we want to collect, followed by a real-world example. On a conceptual level, they can be categorized into general data, meta/environment data, and usage data.

### General Data

The "General Data" category contains information about the process engine:

* Installation - an id that is stored as process engine configuration property
* Product name - the name of the product (i.e., `Camunda BPM Runtime`)
* Product version - the version of the process engine (i.e., `7.X.Y`)
* Product edition - the edition of the product (i.e., either `community` or `enterprise`)

### Meta/Environment Data
The "Meta/Environment Data" category contains information about the environmental setup:

* Database vendor and version
* Application server vendor and version

### Usage Data
The "Usage Data" category contains information about the used features and components of the process engine:

* Commands count - the count of executed commands after the last retrieved data. It could be from the previous 24 hours if the data have been reported then, and the process engine has not been closed during that time. Whenever the process engine is shutdown, the currently collected data is reported immediately.
* Metrics count - the collected metrics are number of root process instance executions started, number of activity instances started or also known as flow node instances, number of executed decision instances, and unique task workers. The counts are collected from the start of the engine or the last reported time if the engine is already running for more than 24 hours.

### Example

```
{
    "installation": "8343cc7a-8ad1-42d4-97d2-43452c0bdfa3",
    "product": {
      "name": "Camunda BPM Runtime",
      "version": "7.13.0",
      "edition": "community",
      "internals": {
        "database": {  
          "vendor": "h2",
          "version": "1.4.190 (2015-10-11)"
        },
        "application-server": {
          "vendor": "Wildfly",
          "version": "WildFly Full 19.0.0.Final (WildFly Core 11.0.0.Final) - 2.0.30.Final"
        },
        "commands": {
          "StartProcessInstanceCmd": {"count": 40},
          "FetchExternalTasksCmd":  {"count": 100}
        },
        "metrics": {
          "root-process-instances": { "count": 936 },
          "flow-node-instances": { "count": 6125 },
          "executed-decision-instances": { "count": 732 },
          "unique-task-workers": { "count": 50 }
        }
      }
    }
}
```

### Logger

A telemetry logger exists to log details about the sent information and error details in case the data couldn't be collected or sent. For further information check the [Logging]({{< ref "/user-guide/logging.md" >}}) page in the User Guide.

### Limitations in Collected Information

In certain scenarios, some of the information will not be retrieved due to the limitations of the implementation.

The application server information cannot be obtained in an embedded process engine setup where no web application (e.g. Tasklist, Cockpit, REST application) is deployed and used.


## How to enable telemetry

### Process Engine Configuration

Use the `initializeTelemetry` configuration [flag][engine-config] to enable the telemetry before starting the process engine. You can simply add it to your process engine configuration:

```
  <property name="initializeTelemetry">true</property>
```

Later on, the telemetry can be enabled/disabled via the engine API.

### Java/Rest API

You can change the telemetry configuration via our API.

To enable/disable telemetry via Java API:

```java
  managementService.toggleTelemetry(true);
```

To achieve the same, you can also use the respective REST API request. For more information, have a look at the [telemetry][telemetry-config-rest] page in the REST API documentation.

## Legal Note

Before you install a Camunda BPM Runtime version >= 7.14.0-alpha1 or activate the telemetry functionality, please make sure that you are authorized to take this step, and that the installation or activation of the [telemetry functionality][engine-config] is not in conflict with any company-internal policies, compliance guidelines, any contractual or other provisions or obligations of your company.

Camunda cannot be held responsible in the event of unauthorized installation or activation of this function.

## Implementation 

In case you want further details, you can have a look at the implementation of the telemetry topic in [our codebase](https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java). The link leads you to the current `master` version of the feature. In case you would like to check the implementation of an old version, adjust the `master` branch to a released tag version, e.g. `7.14.0`.

[engine-config]: {{< ref "/reference/deployment-descriptors/tags/process-engine.md#initializeTelemetry" >}}
[telemetry-config-rest]: {{< ref "/reference/rest/telemetry/port-telemetry.md" >}}

2020-09-07 06:38 UTC, yanavasileva commented on content/introduction/telemetry.md
> +## Collected Data
I applied the suggestions, thank you for the feedback.

2020-09-07 06:40 UTC, merged