docs(update): Add section about Cockpit Plugins
camunda/camunda-docs-manual pull request #689
Opened 2020-09-14 13:27 UTC by marstamm

related to CAM-11443

2020-09-28 13:56 UTC, tasso94 requested changes
Looks good to me in general. However, we should also document the following points:
* The structure of `bpmnJs.additionalModules` changed
* We should document the implications that no preconfigured HTTP client is available:
   * How can I get the CSRF token?
   * How can I get the API paths?
   * Is there any recommendation what I should use (i.e., fetch)?
* The CSS classes of the header changed, so the ["Logo and Header Color"](https://docs.camunda.org/manual/develop/webapps/cockpit/extend/configuration/#logo-and-header-color) example does not work anymore
  * I know from many cases that users make use of customizing the header
  * We should document this change in the migration guide and update the example
* Can we bring back the infographic about "The Nature of a Cockpit Plugin"?
* ["Advanced Styles Customization"](https://docs.camunda.org/manual/develop/webapps/cockpit/extend/configuration/#advanced-styles-customization)
   * Can we update the whole paragraph? 
   * Can we mention in the migration guide that this is deprecated and will be removed soon?

2020-10-01 11:41 UTC, marstamm commented
Great catches, thank you @tasso94 !

### HTTP client:
 I see this as a guide to migrate using AngularJS, therefore I would not recommend `fetch` to the users. In the documentation and examples to write **new** Plugins, we already use `fetch`. If the User did not change the CSRF cookie name, the default `$http` provider will pick it up from the cookies.
I still added a paragraph about it in case they changed the cookie name or want to migrate away from AngularJS.

### "Advanced Styles Customization"
This might be difficult for the new build as it is a mix of scss and less - and the scss result has a hashed file name. I think we should remove the section completely and users should only use the `user-styles.css` to override the camunda styles

### Infographic
I never saw much value in the graphic... If you think it is important, I suggest we create a follow-up ticket for it

2020-10-01 12:25 UTC, tasso94 approved these changes
Looks good. Just fixed two small things.

2020-10-01 12:25 UTC, tasso94 commented on content/update/minor/713-to-714/_index.md
>  1. For developers: [New Engine Dependency - Connect](#new-engine-dependency-connect)
```suggestion
1. For developers: [New Engine Dependency - Connect](#new-engine-dependency-connect)
1. For developers: [Cockpit Style Customizations](#style-customizations)
```

2020-10-01 12:25 UTC, tasso94 commented on content/update/minor/713-to-714/_index.md
> +# Style Customizations
```suggestion
# Cockpit Style Customizations
```
Makes it consistent to the headlines below.

2020-10-01 13:40 UTC, merged