CAM-12201: feat(crdb): add crdb support docs
camunda/camunda-docs-manual pull request #697
Opened 2020-09-16 11:51 UTC by koevskinikola

Related to CAM-12201

2020-09-22 15:20 UTC, ThorbenLindhauer requested changes
I like the restructuring of the database section. For the CockroachDB docs, I think we should only try to explain the *why* if we can do that in a very clear and understandable way. Else we should just stick to the *what*.

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +should be set to 0. This will effectively disable the CockroachDB-specific Command retry mechanism, and
This can be shortened a bit, e.g.

In this case, we suggest to disable the retry mechanism by setting the `commandRetries` configuration property to 0. This will allow the ...

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +# Differences between CockroachDB and other databases
This section title is misleading, because the previous section is also about differences between CockroachDB and other databases. If we want to separate it into "behavior with alternatives" and "behavior without alternatives", then we should call the sections accordingly.

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +that the JDBC driver will wait for a response from the database. However, CockroachDB currently doesn't
I suggest to remove the "However, " here and in the next paragraph as it makes it sound more negative than necessary in my opinion.

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +have on the data included in the transaction. Since the lease time is hard-coded to 5 minutes, transactions
Let's replace "hard-coded". It is a very informal and overly specific term. I suggest to remove the first part of the sentence, I think we don't lose any information given that the second paragraph already says this is not configurable.

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +this would violate this rule ([CockroachDB docs](https://www.cockroachlabs.com/docs/v20.1/demo-serializable.html)).
This is very imprecise:

* It suggests that transactions on other isolation levels leave a database in an instable state
* It suggests that there can be no parallel transactions with CockroachDB

I recommend to remove this paragraph and just say in the second paragraph: Due to SERIALIZABLE isolation, when a...

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +The previous section explained how CockroachDB implements the `SERIALIZABLE` transaction isolation level,
This *previous section* reference is unclear.

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +determine the Process Instance (aka parent execution) of each Task (execution) used in a given process.
It's not clear that this happens only with foreign keys on the same table. Let's be a bit less precise (because we don't understand this problem in its entirety) and just give the example with the execution table.

2020-09-22 15:20 UTC, ThorbenLindhauer commented on content/reference/deployment-descriptors/tags/process-engine.md
> +        <b>Only used with CockroachDB.</b> Specifies how many times a Command will be retried before a <code>CrdbTransactionRetryException</code> is reported to the caller (more details <a href="{{<
Let's link back to the CRDB documentation that explains to which APIs this applies.

2020-09-24 08:49 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +Whenever the Process Engine detects a concurrency conflict between transactions, it reports an
Good to know, I usually capitalize it. Will stop doing it :)

2020-09-24 08:52 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +The role of the pessimistic locks in these Commands is not to prevent concurrent modification on the
Fixed together with the other review hints.

2020-09-24 09:11 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +concurrent startup will fail and be retried instead of waiting to acquire a pessimistic lock. The number
Added together with the other suggestions.

2020-09-24 09:12 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +mechanism section](#custom-cockroachdb-transaction-retry-mechanism). Once the retires are exausted, the
Fixed. Ran the whole text through Grammarly.

2020-09-24 09:35 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +mechanism.
I like it! I will rephrase the section and fit these points in there.

2020-09-24 09:39 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +handled according to the use-case.
I'm not sure about this, and we definitely don't test this case. However, the scenario is similar to the unsupported historical OLEs. There, the user must handle the rollback of any interactions with external systems.

The idea was to offer an alternative, if the feature must be used. If we classify this as a "hard" limitation without alternatives, I would move it to the section below.

2020-09-24 12:14 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +handled according to the use-case.
I removed the offered alternative, and moved the section to the limitations without alternatives.

2020-09-24 12:37 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +As a result of this replacement, multiple Process Engine startups will take longer to finish, as each
Added an additional section that describes what happens when a process engine is started (history cleanup job configuration, determining history level, telemetry and installation id initialization).

2020-09-24 13:39 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +* `HistoryCleanupCmd`
The refactoring here will repeat what is described in the retry mechanism section, but I think it will be more readable this way.

2020-09-25 09:00 UTC, ThorbenLindhauer requested changes
Thanks for making the changes, it reads much better now in my opinion. Please have a look at the remaining comments. Also, please create a PR for https://docs.camunda.org/enterprise/announcement/.

2020-09-25 09:00 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * {{< javadocref page="?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-" text="RepositoryServiceImpl#deployWith
I'm not sure the links are correct. On localhost, it generates `http://localhost:1313/reference/javadoc/?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-`. Replacing `http://localhost:1313` by `https://docs.camunda.org` leads nowhere.

2020-09-25 09:00 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * {{< javadocref page="?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-" text="RepositoryServiceImpl#deployWith
This entry can be removed, because it is internal API that is only used by `DeploymentBuilder#deployWithResult`.

2020-09-25 09:00 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * By starting the job executor with ({{< javadocref page="?org/camunda/bpm/engine/impl/jobexecutor/JobExecutor.html#start--" text="JobExecutor#start()" >}}).
I like the description of the affected APIs much better now and believe they are easier relatable for users. For the last point here, maybe it is also okay to omit the detail bullet point, as most people don't start the job executor explicitly. Instead, we can consider linking to https://docs.camunda.org/manual/7.13/user-guide/process-engine/the-job-executor/#job-acquisition.

2020-09-25 09:00 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * {{< javadocref page="?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-" text="RepositoryServiceImpl#deployWith
Same here, let's not reference internal API.

2020-09-25 10:23 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * {{< javadocref page="?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-" text="RepositoryServiceImpl#deployWith
The correct replacement is `https://docs.camunda.org/manual/latest`.

I used an existing `javadocref`shortcode as an example:

```
{{< javadocref page="?org/camunda/bpm/engine/ProcessEngineConfiguration.html" text="ProcessEngineConfiguration bean" >}}
```

* This is resolved to https://docs.camunda.org/manual/latest/reference/javadoc/?org/camunda/bpm/engine/ProcessEngineConfiguration.html
* And when clicked, it redirects to https://docs.camunda.org/javadoc/camunda-bpm-platform/7.14/?org/camunda/bpm/engine/ProcessEngineConfiguration.html

Unfortunately, these links don't work with method references. They just redirect to the class page, ignoring the method "selector/id" in the URL.

I'll try to create an additional shortcode that will allow us to generate the correct URL directly, and redirect to methods directly.

2020-09-25 10:55 UTC, koevskinikola commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * {{< javadocref page="?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-" text="RepositoryServiceImpl#deployWith
UPDATE:
@ThorbenLindhauer creating a shortcode for this is not straightforward since it seems like the `manual/{version}` URL segment is appended externally, and this needs to be replaced with `javadoc/camunda-bpm-platform/{version}` for the javadoc URL to work correctly and redirect to the method section (the `?` sign should also be removed).

I think we should leave it as it is and create a ticket for this issue. What do you think?

2020-09-25 11:15 UTC, ThorbenLindhauer commented on content/user-guide/process-engine/database/cockroachdb-configuration.md
> +  * {{< javadocref page="?org/camunda/bpm/engine/impl/RepositoryServiceImpl.html#deployWithResult-org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl-" text="RepositoryServiceImpl#deployWith
Yes, sounds good.

2020-09-25 12:51 UTC, ThorbenLindhauer approved these changes
Looks good, thank you.

2020-09-25 13:01 UTC, merged