CAM-12097: chore(docs): create a single page for licence info
camunda/camunda-docs-manual pull request #706
Opened 2020-09-22 09:31 UTC by koevskinikola

* Add a single page dedicated to the Camunda License usage and retrieval
  methods.
* Adjust the doc sections where License use is described to point to the
  dedicated License page.

Related to CAM-12097

2020-09-22 12:06 UTC, mboskamp commented on content/user-guide/license-use.md
> +This method can be used in any scenario, i.e. environment setup. The license key can be set via the
```suggestion
This method can be used in any scenario, e.g. environment setup. The license key can be set via the 
```
I think this should be e.g. instead of i.e., right?
e.g. = for example
i.e. = that is

2020-09-22 12:13 UTC, mboskamp requested changes

2020-09-22 12:13 UTC, mboskamp commented on content/user-guide/license-use.md
> +This is another method that can be applied in any scenario, i.e. environment setup. The license key will be
Same as above

2020-09-22 12:13 UTC, mboskamp commented on content/user-guide/license-use.md
> +automatically loaded in the database table unless a license key is already present.
```suggestion
automatically loaded in the database table unless a valid license key is already present.
```

2020-09-22 12:13 UTC, mboskamp commented on content/user-guide/license-use.md
> +Camunda Run, and other Spring Boot applications that use the Camunda Spring Boot Starter, can provide license
```suggestion
Camunda Run, and other Spring Boot applications (including Camunda BPM RPA Bridge) that use the Camunda Spring Boot Starter, can be provided with license 
```

2020-09-22 12:15 UTC, mboskamp commented
Nice work @koevskinikola! I only have a few tiny improvement suggestions.

2020-09-24 13:45 UTC, koevskinikola commented on content/user-guide/license-use.md
> +automatically loaded in the database table unless a license key is already present.
Will add it with the rest of the review hint implementations.

2020-09-24 13:45 UTC, koevskinikola commented on content/user-guide/license-use.md
> +Camunda Run, and other Spring Boot applications that use the Camunda Spring Boot Starter, can provide license
Same as above.

2020-09-24 13:58 UTC, koevskinikola commented on content/user-guide/license-use.md
> +This method can be used in any scenario, i.e. environment setup. The license key can be set via the
I'm using "environment setup" in the same way as "scenario" here. I think the usage of "i.e." is correct. 

Environment setup would be the combination of OS+AS+DB+JDK (and any other underlying technologies used to run the engine, e.g. containers, framework). 

Scenario is more specific, previously we have used to term do describe setting up the engine in a cluster topology, or with multi tenancy. 

I think they can be used interchangeably in the context of licenses, but if only one should be used, I would go with "environment setup" since it's more general.

What do you think @mboskamp ?

2020-09-24 13:59 UTC, koevskinikola commented on content/user-guide/license-use.md
> +This is another method that can be applied in any scenario, i.e. environment setup. The license key will be
The same comment from above applies here.

2020-09-24 14:08 UTC, koevskinikola commented on content/user-guide/license-use.md
> +This method can be used in any scenario, i.e. environment setup. The license key can be set via the
I dug around our docs a bit, so I think my changes would fit nicely:

* We use `Deployment Scenarios` to describe the topology model. E.g. embedded engine, container-managed, standalone, cluster model or multi-tenancy model.
* We use environment (setup), to describe the combination of OS+AS+DB+JDK+framework. This fits with how a license can be added: directory in OS, Java API, Java classpath, URL or Webapp UI. They are all part of some environment.

2020-09-25 05:42 UTC, mboskamp commented on content/user-guide/license-use.md
> +This method can be used in any scenario, i.e. environment setup. The license key can be set via the
Alright, makes sense.

2020-09-25 05:42 UTC, mboskamp approved these changes

2020-09-25 09:41 UTC, merged