add backoff description
camunda/camunda-docs-manual pull request #711
Opened 2020-09-24 18:32 UTC by ingorichtsmeier

as many forum question like this: https://forum.camunda.org/t/job-executor-taking-longer-time-to-complete/22723 came along it is worth to mention the backoff in the docs.

2020-09-25 13:31 UTC, mboskamp requested changes
Nice addition! Thanks @ingorichtsmeier. Please have a look at two small changes I proposed.

2020-09-25 13:31 UTC, mboskamp commented on content/user-guide/process-engine/the-job-executor.md
> +The Job Executor uses a backoff strategy to avoid acquisition conflicts in clusters and to reduce the database load when no jobs are due. The second point may result in a delay between job creation a
```suggestion
The Job Executor uses a backoff strategy to avoid acquisition conflicts in clusters and to reduce the database load when no jobs are due. The second point may result in a delay between job creation and job execution as the job acquisition by default doubles the delay to the next acquisition run. 
```

2020-09-25 13:31 UTC, mboskamp commented on content/user-guide/process-engine/the-job-executor.md
> +The default maximum wait time to set to 60 seconds. You can decrease the delay by setting the configuration parameter `maxWait` to a value lower than 60000 milliseconds.
```suggestion
The default maximum wait time is 60 seconds. You can decrease the delay by setting the configuration parameter `maxWait` to a value lower than 60000 milliseconds.
```

2020-10-06 09:25 UTC, ingorichtsmeier commented
Hi @mboskamp,

glad that you find my typos, I accepted your change and it should be ready to merge...

2020-10-06 11:49 UTC, merged