Fix inconsistencies and grammatical errors
camunda/camunda-docs-manual pull request #728
Opened 2020-10-03 15:19 UTC by Recal

2020-10-03 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-manual?pullRequest=728) it.</sub>

2020-10-09 06:44 UTC, tmetzke requested changes
Hey @Recal,

thanks for working on this.

Some remarks:
* I do not see any errors with the heading levels with the version on `master`, I would have to decline your changes to that
* The markdown is supposed to be in the note to show that this is possible, so I would have to decline that as well

The typos and capitalizations are fine 👍 

If you are willing to change your PR in those regards we will happily merge it. 👍 

Best,
Tobias

2020-10-09 06:44 UTC, tmetzke commented on README.md
> +* Full markdown is supported.
The idea of this part is to show that you can add full markdown in the note, so that change does not improve anything

2020-10-09 06:44 UTC, tmetzke commented on README.md
> +## How can I add an image?
That is correct as-is

2020-10-09 06:44 UTC, tmetzke commented on README.md
> +#### How can I reference to the Javadocs?
That is correct as-is

2020-10-09 06:44 UTC, tmetzke commented on README.md
> +#### How can I add a note?
That is correct as-is

2020-10-09 06:44 UTC, tmetzke commented on README.md
> +#### How can I add an "EE only note"?
That is correct as-is

2020-10-09 06:44 UTC, tmetzke commented on README.md
> +#### How can I highlight code lines?
That is correct as-is

2020-10-09 19:11 UTC, Recal commented
Thank you for reviewing my PR, now that I look at it there was no real reason to change the header sizes and I have fixed it accordingly. :+1:

2020-10-13 12:36 UTC, tmetzke reviewed
looks good, just one heading that you missed 👍 
I'll commit the suggestion and merge the contribution.
Thanks again, also for changing after review 😃 

Best,
Tobias

2020-10-13 12:36 UTC, tmetzke commented on README.md
> +### How can I reference the image?
That one is meant as a sub-element of "How can I add an image?"

```suggestion
#### How can I reference the image?
```

2020-10-13 12:37 UTC, tmetzke approved these changes

2020-10-13 12:38 UTC, merged