Added metrics
camunda/camunda-docs-manual pull request #872
Opened 2021-03-05 15:59 UTC by superbeagle

Added root-process-instance-start, task-worker, and executed-decision-instances to metrics REST API metric names.

2021-03-17 09:45 UTC, mboskamp requested changes
Hi @superbeagle, thanks for adding the missing metrics. I think the task metric is called `unique-task-workers` instead of `task-worker` (see https://docs.camunda.org/manual/latest/user-guide/process-engine/metrics/ and https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/management/Metrics.java#L81.)

Otherwise it looks good to me :)

2021-03-17 09:45 UTC, mboskamp commented on content/reference/rest/metrics/get-metrics-interval.md
> +      <code>task-worker</code>
```suggestion
      <code>unique-task-workers</code>
```

2021-03-17 09:45 UTC, mboskamp commented on content/reference/rest/metrics/get-metrics-sum.md
> +      <code>task-worker</code>,
```suggestion
      <code>unique-task-workers</code>,
```

2021-03-29 06:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=872) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-manual?pullRequest=872) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: superbeagle<br/>:x: tasso94<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-manual?pullRequest=872) it.</sub>

2021-03-29 06:44 UTC, merged

2022-07-01 07:49 UTC, tmetzke commented on content/reference/rest/metrics/get-metrics-interval.md
> +      <code>unique-task-workers</code>
For future reference: the task worker metric is NOT supported in the interval endpoint, only in the sum endpoint