docs(forms): add referencing for camunda-forms
camunda/camunda-docs-manual pull request #877
Opened 2021-03-11 08:16 UTC by marstamm

related to CAM-13101

2021-03-15 16:47 UTC, tasso94 requested changes
I have some thoughts to consider:
* Can we explain how variables map to the camunda form fields?
* Can we move the contents of `Reference -> Forms` to `Reference -> Forms -> Embedded Forms`, add another page `Reference -> Forms -> Camunda Forms`
  * The `Camunda Forms` page could contain one sentence and a link to the documentation provided by the Modeler Team
  * Like this, it is clear for the user that the Embedded Forms documentation does not apply to Camunda Forms
* A bit off-topic but still interesting: the screenshots on that page look very old. Why is the creation not automated?

2021-03-15 16:47 UTC, tasso94 commented on content/user-guide/task-forms/_index.md
> +# Camunda Forms
I cannot comment on line 18 so I will put it here: can we add the "Camunda Forms" to the list of supported forms?

2021-03-15 16:53 UTC, marstamm commented
Very good points, I will adjust the content accordingly. We will also discuss the topic of documentation again in the next wednesday team sync, I'll update you on the outcome.

> A bit off-topic but still interesting: the screenshots on that page look very old. Why is the creation not automated?

Only `generated-forms-example.png` is not automated, probably because the develop profile does not have a generated form in the demo processes

2021-03-22 08:05 UTC, tasso94 approved these changes
Cool improvements! 👍

2021-03-23 14:24 UTC, volkergersabeck requested changes
I made a few suggestions. We should also bring this together with https://github.com/camunda/camunda-docs-manual/tree/CAM-13307

2021-03-23 14:24 UTC, volkergersabeck commented on content/user-guide/task-forms/_index.md
> +Process variables are mapped to form fields where the form key matches the variable name. The form key for this file could be `camunda-forms:deployment:FORM_NAME.form` or `embedded:app:forms/FORM_NAM
We're mixing here the process variables with the form key. Maybe we should split this in two paragraphs explaining each topic separately

2021-03-23 14:24 UTC, volkergersabeck commented on content/user-guide/task-forms/_index.md
> +  JavaFX, REST-based JavaScript web applications and many more.
Who is still doing Java-based front ends?

Let's describe this more neutral, maybe like this:
"When embedding the process engine into a custom application, you can use any value in the form key property as a reference to your custom form. This way, your front-end can ensure to render the correct form for each user task."

2021-03-23 14:24 UTC, volkergersabeck commented on content/user-guide/task-forms/_index.md
> +Camunda Forms are Forms created using the Form builder in the Camunda Modeler. The form schema is stored in `FORM_NAME.form` files. An example file could look like this:
"Camunda Forms are created as separate files using the Camunda Modeler and can be deployed together with the process models."

There is no "form builder" in the Modeler

2021-03-23 14:24 UTC, volkergersabeck commented on content/user-guide/task-forms/_index.md
> +2. [Camunda Forms](#camunda-forms) offer a form builder in the Camunda Modeler and can be used for less complex forms.
offer visual editing of forms in the Camunda Modeler and can be used for less complex forms.

2021-03-23 14:24 UTC, volkergersabeck commented on content/user-guide/task-forms/_index.md
> +```JSON
I'm not sure whether we should post the raw JSON in here. I'd prefer to have a screenshot of the Modeler and not show any code. The whole purpose of Camunda Forms is that people don't need to code them.

2021-03-23 14:24 UTC, volkergersabeck commented on content/user-guide/task-forms/_index.md
I would suggest that we add one more sentence like "More detailed information can be found in the [Camunda Forms Documentation](link to new Modeler forms page)"

Idea is: 
- user guide explains how to configure a user task to use either embedded or Camunda forms
- reference explains technical details mostly on embedded forms
- Modeler explains usage of form editing and capabilities of Camunda forms

2021-03-23 14:24 UTC, volkergersabeck commented on content/reference/forms/camunda-forms/_index.md
> +Camunda Forms are created in the Camunda Modeler. More detailed information can be found in the [User Guide]({{< ref "/user-guide/task-forms/_index.md#camunda-forms" >}}).
I guess you already planned to do this:
"More detailed information can be found in the [Camunda Forms Documentation](link to new Modeler forms page)"

Idea is: 
- User guide explains how to configure a user task to use either embedded or Camunda forms
- Reference explains technical details mostly on embedded forms
- Modeler explains usage of form editing and capabilities of Camunda forms

2021-03-24 11:44 UTC, MaxTru commented
As discussed with Volker and Martin: I will add a commit to the branch for the Camunda Modeler section. Then the PR is a complete end-2-end package.

2021-03-24 12:45 UTC, MaxTru commented on content/user-guide/task-forms/_index.md
Done

2021-03-24 12:45 UTC, MaxTru commented on content/reference/forms/camunda-forms/_index.md
> +Camunda Forms are created in the Camunda Modeler. More detailed information can be found in the [User Guide]({{< ref "/user-guide/task-forms/_index.md#camunda-forms" >}}).
Done

2021-03-24 12:50 UTC, MaxTru commented on content/user-guide/task-forms/_index.md
> +Process variables are mapped to form fields where the fields key matches the variable name.
@marstamm @volkergersabeck shall we add something like

```suggestion
Process variables are mapped to form fields where the fields key matches the variable name during form rendering as well as form submission.
```

2021-03-24 13:13 UTC, MaxTru commented on content/user-guide/task-forms/_index.md
> +Process variables are mapped to form fields where the fields key matches the variable name.
+ Backlink zu [Process Variables](https://docs.camunda.org/manual/latest/user-guide/process-engine/variables/)?

2021-03-24 13:16 UTC, marstamm commented on content/user-guide/task-forms/_index.md
> +Process variables are mapped to form fields where the fields key matches the variable name.
I think that it is implied that it works both ways, so the addition would not be necessary in my opinion.

If you have a strong opinion that this will clear things up, let's add it but change "form rendering" to "form loading" :slightly_smiling_face:

2021-03-24 13:18 UTC, marstamm commented on content/user-guide/task-forms/_index.md
> +Process variables are mapped to form fields where the fields key matches the variable name.
And a backlink is a good Idea, I'll add it :+1:

2021-03-31 13:32 UTC, merged