docs(content): Added Camunda Community Hub Information
camunda/camunda-docs-manual pull request #920
Opened 2021-04-08 20:26 UTC by celanthe

- Added link to the Community Hub to the extensions page
- Added link to the Camunda Community Hub community repository
- Added additional context regarding the Camunda Community Hub

Related to #915

2021-04-08 21:15 UTC, akeller requested changes
Just a couple small things to fix.

2021-04-08 21:15 UTC, akeller commented on content/introduction/extensions.md
> +The [Camunda Community Hub](https://github.com/camunda-community-hub) is a GitHub Organization that serves as the home of Camunda open source community-contributed extensions. You can migrate  extens
> You can migrate  extension, search for existing ones, or help maintainers with contributions.

This sentence doesn't quite make sense. Can you take another look at this @celanthe?

2021-04-08 21:15 UTC, akeller commented on content/introduction/extensions.md
> +You can also visit the Camunda Community Hub's [community repository](https://github.com/camunda-community-hub/community) to learn more about migrating your community extension into the community hub
```suggestion
You can also visit the Camunda Community Hub [community repository](https://github.com/camunda-community-hub/community) to learn more about migrating your community extension into the community hub, benefits to joining the Camunda Community Hub Organization, contributing to an extension, and much more.
```

2021-04-08 21:20 UTC, akeller commented
I just realized this was in the camunda-docs-manual repo, meaning this content lives with the versioned content. We'll need to make sure this persists across all new versions. Shouldn't be a problem, but I wanted to make sure it was known.

2021-04-09 06:31 UTC, yanavasileva commented
I have created CAM-13376 to track the goal and progress of the contribution. Backporting to previous versions will be take care of Runtime team.

2021-04-09 12:34 UTC, ThorbenLindhauer requested changes
The changes look good to me. As with the other PR, I propose we remove the list of extensions from the docs at this point (https://github.com/camunda/camunda-docs-manual/blob/df7051477e0e4872c0d4aa62f98c88bdb8b679fe/content/introduction/extensions.md#list-of-community-extensions) and point people to the hub instead. What do you think?

2021-04-12 13:31 UTC, celanthe reviewed
Made changes requested and submitted a new commit!

2021-04-13 11:46 UTC, ThorbenLindhauer approved these changes

2021-04-13 11:53 UTC, ThorbenLindhauer commented
Hey @celanthe,

Thanks for your contribution, I merged it together with #915 via d1f2fcf.

Cheers,
Thorben

2021-04-13 11:53 UTC, closed without merging