docs(third-party+update+scripting): add Java 15 parts
camunda/camunda-docs-manual pull request #990
Opened 2021-06-09 14:44 UTC by tmetzke

* adds update guide for Java 15 and GraalVM JavaScript
* adds GraalVM JavaScript to scripting guide
* adds script engine configuration to scripting guide
* adds GraalVM JavaScript to TPL list

related to CAM-13518

2021-07-01 12:48 UTC, koevskinikola requested changes
Looks good overall! I found some points that we can discuss if they need to be improved or not.

2021-07-01 12:48 UTC, koevskinikola commented on content/update/minor/715-to-716/_index.md
> +Depending on your [application setup] and use of JavaScript, moving forward with *GraalVM JavaScript* requires different follow-up tasks.
Is the [application setup] formatting meant to be a link?

2021-07-01 12:48 UTC, koevskinikola commented on content/user-guide/process-engine/scripting.md
> +</table>
These properties are part of the `ProcessEngineConfiguration`. Wouldn't it make more sense to add them to the table in https://github.com/camunda/camunda-docs-manual/blob/master/content/reference/deployment-descriptors/tags/process-engine.md#configuration-properties and link to them?

2021-07-01 12:56 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +[Default JavaScript engine]: (#default-javascript-engine)
```suggestion
[application setup]: {{< ref "/introduction/architecture.md#camunda-platform-architecture" >}}
[Pre-Packaged Distributions]: {{< ref "/installation/full/_index.md" >}}
[Camunda Platform Run]: {{< ref "/installation/camunda-bpm-run.md" >}}
[Default JavaScript engine]: #default-javascript-engine
```

2021-07-01 12:57 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +Depending on your [application setup] and use of JavaScript, moving forward with *GraalVM JavaScript* requires different follow-up tasks.
It is a link, yes, defined by the references at the bottom of this document. 😃

2021-07-01 12:58 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +</table>
I was thinking about it, yeah. Sounds like it's more consistent, I will do that 👍

2021-07-06 10:10 UTC, koevskinikola approved these changes
Looks good!

2021-07-06 17:19 UTC, akeller reviewed
This might be somewhere else, but it would be good to have the error message users may see if they are unknowingly running Java 15 and missing their scripting engine. It would also be good to provide folks the terminal command to check what version of Java they are running.

Most of my comments are around punctuation and italics vs. bold. Since we are actively working on our style guide to address some of these topics, I don't expect you to know how to handle them quite yet.

For example, if you want to emphasize 3rd party names, I'd like to move away from _italics_ and use **bold**. I realize this may not be the case across the rest of the documentation, so feel free to ignore those changes for now and we'll make a plan in the future to adhere to the style guide.

2021-07-06 17:19 UTC, akeller commented on content/update/minor/715-to-716/_index.md
> +The Camunda Platform [Pre-Packaged Distributions] and [Camunda Platform Run] can now include *GraalVM JavaScript*.
I would include something like "as of version 7.16" instead of just "now".

2021-07-06 17:19 UTC, akeller commented on content/update/minor/715-to-716/_index.md
> +If you are using [Camunda Platform Run], *GraalVM JavaScript* is already included in your distribution by default. You don't have to consider any further setup tasks to include *GraalVM JavaScript*.
Since what version or date? 7.16 or earlier?

2021-07-06 17:19 UTC, akeller commented on content/user-guide/process-engine/scripting.md
> +* *Groovy*. Configured to only hold weak references to Java methods by setting `#jsr223.groovy.engine.keep.globals` to `weak`.
```suggestion
* **Groovy**. Configured to only hold weak references to Java methods by setting `#jsr223.groovy.engine.keep.globals` to `weak`.
```

Similar to my comment on GraalVM, if you want to emphasize 3rd party names I would make them bold instead.

2021-07-06 17:19 UTC, akeller commented on content/user-guide/process-engine/scripting.md
> +  `polyglot.js.allowHostClassLookup` to `true`.
```suggestion
By default, the following script engines are configured with default options after creation:

*Groovy* - Configured to only hold weak references to Java methods by setting `#jsr223.groovy.engine.keep.globals` to `weak`.

*GraalVM JavaScript* - Configured to allow host acces and host class lookup by setting `polyglot.js.allowHostAccess` and 
  `polyglot.js.allowHostClassLookup` to `true`.
```

This section is a bit awkward to read and look at. I would remove the bullets. I don't love the suggestion I made here though. Maybe a small table?

2021-07-06 17:19 UTC, akeller commented on content/user-guide/process-engine/scripting.md
> +Tomcat, Websphere and Weblogic support providing JVM arguments via environment variables `JAVA_OPTS` or `JAVA_OPTIONS`.
```suggestion
Tomcat, Websphere, and Weblogic support providing JVM arguments via environment variables `JAVA_OPTS` or `JAVA_OPTIONS`. 
```

2021-07-06 17:19 UTC, akeller commented on content/user-guide/process-engine/scripting.md
> +you can change settings on the Script Engine instance provided to that method as shown in the following example:
```suggestion
you can change settings on the script engine instance provided to that method as shown in the following example:
```
I *think* script engine should be lowercase anywhere it isn't ScriptEngine.

2021-07-06 17:19 UTC, akeller commented on content/user-guide/process-engine/scripting.md
> +instance with Nashorn Compatibility Mode enabled:
Same comment here on script engine, but feel free to correct me!

2021-07-07 06:42 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +This section provides guidance on migration tasks for business processes that make use of JavaScript code in any way.
```suggestion
This section provides guidance on migration tasks for processes that make use of JavaScript code in any way.
```

2021-07-07 06:43 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +With this release, we add out-of-the-box support for option #1. You can approach options #2 and #3 as you can with any previous version of Camunda Platform.
```suggestion
With Camunda 7.16, we add out-of-the-box support for option #1. You can approach options #2 and #3 as you can with any previous version of Camunda Platform.
```

2021-07-07 06:45 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +Adding the *GraalVM JavaScript* script engine to your application requires adding two dependencies:
```suggestion
Adding the **GraalVM JavaScript** script engine to your application requires adding two dependencies: 
```

2021-07-07 06:45 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +* [Graaljs Scriptengine](https://search.maven.org/artifact/org.graalvm.js/js-scriptengine)
Good catch! 🙂

2021-07-07 06:46 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +You can also configure the *GraalVM JavaScript* engine to your needs if necessary.
```suggestion
If you are migrating from **Nashorn**, please read the [official Nashorn migration guide]. 
You can also configure the **GraalVM JavaScript** engine to your needs if necessary. 
```

2021-07-07 06:46 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +The JVM registers the *GraalVM JavaScript* engine automatically. The Camunda Platform picks up the script engine and configures it automatically for any occurrence of JavaScript execution in the proc
```suggestion
The JVM registers the **GraalVM JavaScript** engine automatically. The Camunda Platform picks up the script engine and configures it automatically for any occurrence of JavaScript execution in the process engine context. 
```

2021-07-07 06:46 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +If you are using any of our [Pre-Packaged Distributions], *GraalVM JavaScript* can be included in the container of your choice by updating as advised in the [Full Distribution] section above.
```suggestion
If you are using any of our [Pre-Packaged Distributions], **GraalVM JavaScript** can be included in the container of your choice by updating as advised in the [Full Distribution] section above.
```

2021-07-07 06:47 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +If you are migrating from *Nashorn*, please read the [official Nashorn migration guide].
```suggestion
If you are migrating from **Nashorn**, please read the [official Nashorn migration guide].
```

2021-07-07 06:47 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +You can also configure the *GraalVM JavaScript* engine to your needs if necessary.
```suggestion
You can also configure the **GraalVM JavaScript** engine to your needs if necessary. 
```

2021-07-07 06:50 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +If you are using [Camunda Platform Run], *GraalVM JavaScript* is already included in your distribution by default. You don't have to consider any further setup tasks to include *GraalVM JavaScript*.
```suggestion
If you are using any of our [Pre-Packaged Distributions], **GraalVM JavaScript** can be included in the container of your choice by updating to version 7.16 as advised in the [Full Distribution] section above.
If you are updating to version 7.16 of [Camunda Platform Run], **GraalVM JavaScript** is already included in your distribution by default. You don't have to consider any further setup tasks to include **GraalVM JavaScript**.
```

2021-07-07 06:51 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +You can also configure the *GraalVM JavaScript* engine to your needs if necessary.
```suggestion
If you are migrating from **Nashorn**, please read the [official Nashorn migration guide].
You can also configure the **GraalVM JavaScript** engine to your needs if necessary. 
```

2021-07-07 06:52 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +The Camunda Platform [Pre-Packaged Distributions] and [Camunda Platform Run] can now include *GraalVM JavaScript*.
```suggestion
The Camunda Platform [Pre-Packaged Distributions] and [Camunda Platform Run] can include *GraalVM JavaScript* as of version 7.16.
```

2021-07-07 06:53 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +If you run those distributions on any Java version prior to Java 15, the JVM also includes the *Nashorn* scripting engine by default.
```suggestion
If you run those distributions on any Java version prior to Java 15, the JVM also includes the **Nashorn** scripting engine by default.
```

2021-07-07 06:53 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +In effect, you might be automatically migrating from *Nashorn* to *GraalVM JavaScript* depending on the distribution you use and the upgrade procedure you perform.
```suggestion
In effect, you might be automatically migrating from **Nashorn** to **GraalVM JavaScript** depending on the distribution you use and the upgrade procedure you perform.
```

2021-07-07 06:53 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +The following Camunda distributions include *GraalVM JavaScript* by default when updating as advised in the [Full Distribution] section:
```suggestion
The following Camunda distributions include **GraalVM JavaScript** by default when updating as advised in the [Full Distribution] section:
```

2021-07-07 06:54 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +Please consult the [official Nashorn migration guide] to evaluate if migrating to *GraalVM JavaScript* is feasible in your setup.
```suggestion
Please consult the [official Nashorn migration guide] to evaluate if migrating to **GraalVM JavaScript** is feasible in your setup.
```

2021-07-07 06:55 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +  The *Nashorn* scripting engine is not included there anymore.
```suggestion
* Do not add **GraalVM JavaScript** as a library to your distribution. 
  The Camunda Platform executes scripts with languages `javascript` and `ecmascript` as it did before.
  Note that this is not possible on JBoss AS/Wildfly and Camunda Platform Run without further adjustments.
* Set the engine configuration option `scriptEngineNameJavaScript` to a script engine of your choice. 
  The Camunda Platform uses this script engine as the default for all scripts with languages `javascript` and `ecmascript`. 
  Setting this option to `nashorn` enables the previous execution behavior. 
  Note that this is not possible out-of-the-box anymore starting with Java 15. 
  The **Nashorn** scripting engine is not included there anymore.
```

2021-07-07 06:56 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +  Using this, you can migrate to *GraalVM JavaScript* in general and still keep single scripts on the old behavior until ready to migrate.
```suggestion
  Using this, you can migrate to **GraalVM JavaScript** in general and still keep single scripts on the old behavior until ready to migrate.
```

2021-07-07 06:56 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +Furthermore, you can also configure the *GraalVM JavaScript* engine to your needs if necessary.
```suggestion
Furthermore, you can also configure the **GraalVM JavaScript** engine to your needs if necessary. 
```

2021-07-07 06:58 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +Script Engine instance is sufficient for you. By overriding the `#configureScriptEngines(String, ScriptEngine)` method of the `DefaultScriptEngineResolver`,
```suggestion
script engine instance is sufficient for you. By overriding the `#configureScriptEngines(String, ScriptEngine)` method of the `DefaultScriptEngineResolver`, 
```

2021-07-07 06:59 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +If you need more flexibility in configuring a Script Engine, you can override a method further up the chain in the Script Engine creation
```suggestion
If you need more flexibility in configuring a script engine, you can override a method further up the chain in the script engine creation
```

2021-07-07 06:59 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +or provide your own plain implementation of the interface. Have a look at the following example that provides a custom *GraalVM JavaScript*
```suggestion
or provide your own plain implementation of the interface. Have a look at the following example that provides a custom **GraalVM JavaScript** 
```

2021-07-07 07:00 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +JavaScript code executes on *GraalVM JavaScript* with preference in the process engine context if this script engine is available.
```suggestion
**JavaScript** code execution is part of the Java Runtime (JRE) with the **Nashorn** script engine until Java 14 and thus only there available out of the box.
We include **GraalVM JavaScript** in the pre-packaged Camunda distributions as a replacement regardless of the JRE version.
JavaScript code executes on **GraalVM JavaScript** with preference in the process engine context if this script engine is available.
```

2021-07-07 07:00 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +Set this value to `nashorn` to configure the process engine to use the *Nashorn* script engine by default.
```suggestion
Set this value to `nashorn` to configure the process engine to use the **Nashorn** script engine by default.
```

2021-07-07 07:03 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +You can configure the Script Engines by any of the following:
```suggestion
You can configure the script engines by any of the following:
```

2021-07-07 07:05 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +This version of Java not only adds new features but also removes the default JavaScript engine called *Nashorn*.
```suggestion
This version of Java not only adds new features but also removes the default JavaScript engine called **Nashorn**.
```

2021-07-07 07:05 UTC, tmetzke commented on content/update/minor/715-to-716/_index.md
> +In order to provide a reliable behavior on those platforms, the Camunda Platform preferrably executes code for languages `javascript` and `ecmascript` on *GraalVM JavaScript* if it is available.
```suggestion
In order to provide a reliable behavior on those platforms, the Camunda Platform preferrably executes code for languages `javascript` and `ecmascript` on **GraalVM JavaScript** if it is available.
```

2021-07-07 07:06 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +  We include *Groovy* in the pre-packaged Camunda distributions.
```suggestion
  We include **GraalVM JavaScript** in the pre-packaged Camunda distributions. 
  Consult [JavaScript Considerations](#javascript-considerations) for further information.
  
  We include **Groovy** in the pre-packaged Camunda distributions.
```

2021-07-07 07:07 UTC, tmetzke commented on content/user-guide/process-engine/scripting.md
> +* *GraalVM JavaScript*. Configured to allow host acces and host class lookup by setting `polyglot.js.allowHostAccess` and
```suggestion
* **GraalVM JavaScript**. Configured to allow host acces and host class lookup by setting `polyglot.js.allowHostAccess` and 
```

2021-07-07 08:00 UTC, merged

2021-07-07 08:00 UTC, tmetzke commented
Thanks again to all reviewers! 💯 🚀